In [5]:
from pathlib import Path

import pandas as pd

BASE_DIR = Path("../")

BRONZE_DIR = (
    BASE_DIR / "data/02-bronze"
)

ARQ_DESPESA = (
    BRONZE_DIR / "despesa.parquet"
)

df_despesa = pd.read_parquet(
    ARQ_DESPESA 
)

df_despesa.head()

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,NaN,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.0,0.0,-1,NaN,-1
1,2026-04-25,16:26:12,2025,NaN,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.0,0.0,-1,NaN,-1
2,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,CE,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.0,0.0,-1,NaN,-1
3,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,MS,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.0,0.0,-1,NaN,-1
4,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,SP,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.0,0.0,-1,NaN,-1

## Validando Schema

Verifique:

snake_case;
padronização;
colunas esperadas.

In [6]:
df_despesa.columns.tolist()

['dt_geracao',
 'hh_geracao',
 'aa_exercicio',
 'tp_despesa',
 'cd_tp_esfera_partidaria',
 'ds_tp_esfera_partidaria',
 'sg_uf',
 'cd_municipio',
 'nm_municipio',
 'nr_zona',
 'nr_cnpj_prestador_conta',
 'sg_partido',
 'nm_partido',
 'cd_tp_documento',
 'ds_tp_documento',
 'nr_documento',
 'aa_aidf',
 'nr_aidf',
 'cd_tp_fornecedor',
 'ds_tp_fornecedor',
 'nr_cpf_cnpj_fornecedor',
 'nm_fornecedor',
 'ds_gasto',
 'dt_pagamento',
 'vl_gasto',
 'vl_pagamento',
 'vl_documento',
 'cd_fonte_despesa',
 'ds_fonte_despesa',
 'sq_despesa']

## Dtypes

Verifique:

datas em datetime;
valores em float;
não sobrou object indevido.

In [7]:
df_despesa.dtypes

dt_geracao                 datetime64[us]
hh_geracao                            str
aa_exercicio                        int64
tp_despesa                            str
cd_tp_esfera_partidaria               str
ds_tp_esfera_partidaria               str
sg_uf                                 str
cd_municipio                          str
nm_municipio                          str
nr_zona                             int64
nr_cnpj_prestador_conta               str
sg_partido                            str
nm_partido                            str
cd_tp_documento                       str
ds_tp_documento                       str
nr_documento                          str
aa_aidf                             int64
nr_aidf                               str
cd_tp_fornecedor                      str
ds_tp_fornecedor                      str
nr_cpf_cnpj_fornecedor                str
nm_fornecedor                         str
ds_gasto                              str
dt_pagamento               datetime64[us]
vl_gasto                          float64
vl_pagamento                      float64
vl_documento                      float64
cd_fonte_despesa                      str
ds_fonte_despesa                      str
sq_despesa                          int64
dtype: object

## Shape

In [8]:
df_despesa.shape

(196033, 30)

## NULLs

In [9]:
(
    df_despesa
    .isna()
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

nm_municipio               166027
nr_documento                47054
ds_tp_documento             31431
cd_tp_documento             31431
cd_tp_fornecedor             3348
ds_tp_fornecedor             3348
nm_fornecedor                3348
nr_cpf_cnpj_fornecedor       3348
ds_gasto                     2793
dt_pagamento                 2793
tp_despesa                   2793
ds_fonte_despesa             2793
hh_geracao                      0
aa_exercicio                    0
nm_partido                      0
sg_partido                      0
nr_cnpj_prestador_conta         0
nr_zona                         0
sg_uf                           0
cd_municipio                    0
dtype: int64

## Valores Monetarios

Verifique:

parsing decimal correto;
sem string;
sem vírgula.

In [15]:
df_despesa[
    ["vl_gasto", "vl_pagamento","vl_documento"]
].describe()

           vl_gasto  vl_pagamento  vl_documento
count  1.960330e+05  1.960330e+05  1.960330e+05
mean   6.197181e+03  6.045245e+03  7.493695e+03
std    5.038810e+04  4.937167e+04  5.567233e+04
min    0.000000e+00  0.000000e+00  0.000000e+00
25%    4.800000e+01  5.000000e+01  6.153000e+01
50%    4.000000e+02  4.000000e+02  5.000000e+02
75%    2.800000e+03  2.790630e+03  3.196450e+03
max    3.821394e+06  3.821394e+06  3.821394e+06

## Datas

In [ ]:
df_despesa[
    "dt_despesa"
].head()

0   2025-08-05
1   2025-08-28
2   2025-10-01
3   2025-12-22
4   2025-04-25
Name: dt_receita, dtype: datetime64[us]

# Exemplo com DuckDB

In [17]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/despesa.parquet'
    )
    LIMIT 20
    """
).df()

df.head(20)

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nr_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
1,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
2,2026-04-25,16:26:12,2025,None,2,ESTADUAL,CE,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
3,2026-04-25,16:26:12,2025,None,2,ESTADUAL,MS,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
4,2026-04-25,16:26:12,2025,None,2,ESTADUAL,SP,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
5,2026-04-25,16:26:12,2025,None,2,ESTADUAL,PR,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
6,2026-04-25,16:26:12,2025,None,2,ESTADUAL,GO,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
7,2026-04-25,16:26:12,2025,None,2,ESTADUAL,PI,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
8,2026-04-25,16:26:12,2025,None,2,ESTADUAL,GO,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
9,2026-04-25,16:26:12,2025,None,2,ESTADUAL,SC,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
10,2026-04-25,16:26:12,2025,None,2,ESTADUAL,RJ,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
11,2026-04-25,16:26:12,2025,None,2,ESTADUAL,RN,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
12,2026-04-25,16:26:12,2025,None,2,ESTADUAL,AM,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
13,2026-04-25,16:26:12,2025,None,2,ESTADUAL,MT,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
14,2026-04-25,16:26:12,2025,None,2,ESTADUAL,AC,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
15,2026-04-25,16:26:12,2025,None,4,MUNICIPAL,MG,4163,BONFINOPOLIS DE MINAS,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
16,2026-04-25,16:26:12,2025,None,4,MUNICIPAL,MA,803,IMPERATRIZ,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
17,2026-04-25,16:26:12,2025,None,4,MUNICIPAL,RS,8609,COLORADO,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
18,2026-04-25,16:26:12,2025,None,4,MUNICIPAL,MT,9067,CUIABA,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
19,2026-04-25,16:26:12,2025,None,4,MUNICIPAL,PR,7481,CAMPO LARGO,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1

In [ ]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        sg_partido,
        SUM(vl_receita) AS vl_total
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 20
    """
).df()

df.head()

     sg_partido      vl_total
0            PL  2.960729e+08
1            PT  2.317026e+08
2           PSD  1.312535e+08
3  REPUBLICANOS  1.274974e+08
4           MDB  1.237678e+08

In [12]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,sg_partido,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,dt_receita,ds_receita,vl_receita
0,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,None,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00
1,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,None,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00
2,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,None,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00
3,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,None,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00
4,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,None,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07