In [2]:
from pathlib import Path

import pandas as pd

BASE_DIR = Path("../")

BRONZE_DIR = (
    BASE_DIR / "data/02-bronze"
)

ARQ_RECEITA = (
    BRONZE_DIR / "receita.parquet"
)

df_receita = pd.read_parquet(
    ARQ_RECEITA
)

df_receita.head()

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,sg_partido,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,dt_receita,ds_receita,vl_receita
0,25/04/2026,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,NaN,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00
1,25/04/2026,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,NaN,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00
2,25/04/2026,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,NaN,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00
3,25/04/2026,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,NaN,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00
4,25/04/2026,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,NaN,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07

## Validando Schema

Verifique:

snake_case;
padronização;
colunas esperadas.

In [3]:
df_receita.columns.tolist()

['DT_GERACAO',
 'HH_GERACAO',
 'CD_TP_ESFERA_PARTIDARIA',
 'DS_TP_ESPERA_PARTIDARIA',
 'SG_UF',
 'CD_MUNICIPIO',
 'NM_MUNICIPIO',
 'NR_ZONA',
 'NR_CNPJ_PRESTADOR_CONTA',
 'sg_partido',
 'nm_partido',
 'CD_TP_ORIGEM_DOACAO',
 'DS_TP_ORIGEM_DOACAO',
 'NR_CPF_CNPJ_DOADOR',
 'NM_DOADOR',
 'CD_TP_ESFERA_PARTIDARIA_DOADOR',
 'DS_TP_ESFERA_PARTIDARIA_DOADOR',
 'SG_UF_DOADOR',
 'CD_MUNICIPIO_DOADOR',
 'NM_MUNICIPIO_DOADOR',
 'NR_ZONA_DOADOR',
 'SQ_CANDIDATO_DOADOR',
 'NR_CANDIDATO_DOADOR',
 'CD_CANDIDATO_CARGO_DOADOR',
 'DS_CANDIDATO_CARGO_DOADOR',
 'CD_TP_FONTE_RECURSO',
 'DS_TP_FONTE_RECURSO',
 'CD_TP_NATUREZA_RECURSO',
 'DS_TP_NATUREZA_RECURSO',
 'CD_TP_ESPECIE_RECURSO',
 'DS_TP_ESPECIE_RECURSO',
 'NR_RECIBO_DOACAO',
 'NR_DOCUMENTO',
 'dt_receita',
 'ds_receita',
 'vl_receita']

## Dtypes

Verifique:

datas em datetime;
valores em float;
não sobrou object indevido.

In [4]:
df_receita.dtypes

DT_GERACAO                                   str
HH_GERACAO                                   str
CD_TP_ESFERA_PARTIDARIA                      str
DS_TP_ESPERA_PARTIDARIA                      str
SG_UF                                        str
CD_MUNICIPIO                                 str
NM_MUNICIPIO                                 str
NR_ZONA                                      str
NR_CNPJ_PRESTADOR_CONTA                      str
sg_partido                                   str
nm_partido                                   str
CD_TP_ORIGEM_DOACAO                          str
DS_TP_ORIGEM_DOACAO                          str
NR_CPF_CNPJ_DOADOR                           str
NM_DOADOR                                    str
CD_TP_ESFERA_PARTIDARIA_DOADOR               str
DS_TP_ESFERA_PARTIDARIA_DOADOR               str
SG_UF_DOADOR                                 str
CD_MUNICIPIO_DOADOR                          str
NM_MUNICIPIO_DOADOR                          str
NR_ZONA_DOADOR                            object
SQ_CANDIDATO_DOADOR                          str
NR_CANDIDATO_DOADOR                          str
CD_CANDIDATO_CARGO_DOADOR                    str
DS_CANDIDATO_CARGO_DOADOR                    str
CD_TP_FONTE_RECURSO                          str
DS_TP_FONTE_RECURSO                          str
CD_TP_NATUREZA_RECURSO                       str
DS_TP_NATUREZA_RECURSO                       str
CD_TP_ESPECIE_RECURSO                        str
DS_TP_ESPECIE_RECURSO                        str
NR_RECIBO_DOACAO                             str
NR_DOCUMENTO                                 str
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
dtype: object

## Shape

In [5]:
df_receita.shape

(194844, 36)

## NULLs

In [6]:
(
    df_receita
    .isna()
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

NR_ZONA_DOADOR                    194844
NR_CANDIDATO_DOADOR               194462
CD_CANDIDATO_CARGO_DOADOR         194462
SQ_CANDIDATO_DOADOR               194462
DS_CANDIDATO_CARGO_DOADOR         194462
NR_ZONA                           193917
NR_DOCUMENTO                      167300
CD_MUNICIPIO_DOADOR               152784
NM_MUNICIPIO_DOADOR               152784
CD_MUNICIPIO                      148413
NM_MUNICIPIO                      148413
NR_CPF_CNPJ_DOADOR                 23384
NM_DOADOR                          23384
NR_RECIBO_DOACAO                   22948
DS_TP_ORIGEM_DOACAO                 6419
CD_TP_ORIGEM_DOACAO                 6419
DS_TP_ESFERA_PARTIDARIA_DOADOR      6419
SG_UF_DOADOR                        6419
CD_TP_ESFERA_PARTIDARIA_DOADOR      6419
DS_TP_ESPECIE_RECURSO               3369
dtype: int64

## Valores Monetarios

Verifique:

parsing decimal correto;
sem string;
sem vírgula.

In [7]:
df_receita[
    "vl_receita"
].describe()

count    1.948440e+05
mean     7.960730e+03
std      2.217228e+05
min      0.000000e+00
25%      3.975000e+01
50%      8.000000e+01
75%      2.500000e+02
max      3.726423e+07
Name: vl_receita, dtype: float64

## Datas

In [8]:
df_receita[
    "dt_receita"
].head()

0   2025-08-05
1   2025-08-28
2   2025-10-01
3   2025-12-22
4   2025-04-25
Name: dt_receita, dtype: datetime64[us]

# Exemplo com DuckDB

In [ ]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        SUM(vl_receita) AS vl_total
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    LIMIT 20
    """
).df()

df.head()

1,551,100,524.4500017

       vl_total
0  1.551101e+09

In [ ]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        sg_partido,
        SUM(vl_receita) AS vl_total
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 20
    """
).df()

df.head()

     sg_partido      vl_total
0            PL  2.960729e+08
1            PT  2.317026e+08
2           PSD  1.312535e+08
3  REPUBLICANOS  1.274974e+08
4           MDB  1.237678e+08

In [12]:
import duckdb

df = duckdb.sql(
    """
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/receita.parquet'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,sg_partido,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,dt_receita,ds_receita,vl_receita
0,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,None,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00
1,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,None,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00
2,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,None,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00
3,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,None,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00
4,25/04/2026,16:24:44,0,NACIONAL,BR,None,None,None,32206989000180,AGIR,...,OUTROS RECURSOS,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,None,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07