# Com DuckDB

In [2]:
import duckdb

## Visualiza todos os dados

In [ ]:
PARQUET_BRONZE_FILE_NAME = ["../data/02-bronze/classificacao_despesa.parquet",
                            "../data/02-bronze/cnpj.parquet",
                            "../data/02-bronze/despesa.parquet",
                            "../data/02-bronze/receita.parquet"
                            ]

PARQUET_SILVER_FILE_NAME = ["../data/03-silver/classificacao_despesa.parquet",
                            "../data/03-silver/cnpj.parquet",
                            "../data/03-silver/despesa.parquet",
                            "../data/03-silver/receita.parquet"
                            ]

PARQUET_GOLD_FILE_NAME = ["../data/04-gold/despesa_enriquecida.parquet",
                    "../data/04-gold/partido_ano_despesa.parquet",
                    "../data/04-gold/partido_ano_receita.parquet",
                    "../data/04-gold/receita_enriquecida.parquet"]

In [ ]:
from IPython.display import display
import duckdb

for file in PARQUET_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        LIMIT 100
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    display(df.head())

## Broze

### Receita

### Despesa

In [3]:
PARQUET_FILE_NAME = "despesa.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    LIMIT 20
    """
).df()

df.head()

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,DS_GASTO,DT_PAGAMENTO,VR_GASTO,VR_PAGAMENTO,VR_DOCUMENTO,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:26:12,2025,#NULO#,1,Distrital,DF,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
1,25/04/2026,16:26:12,2025,#NULO#,1,Distrital,DF,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
2,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,CE,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
3,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,MS,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
4,25/04/2026,16:26:12,2025,#NULO#,2,Estadual,SP,-1,#NULO#,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1

In [24]:
PARQUET_FILE_NAME = "classificacao_despesa.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,DESPESA,CLASSIFICACAO
0,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO
1,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,ADMINISTRATIVO
2,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,ADMINISTRATIVO
3,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,ADMINISTRATIVO
4,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,FINALÍSTICO
...,...,...
155,SEGURANCA E VIGILANCIA - DESPESAS ELEITORAIS ...,FINALÍSTICO
156,"DESPESAS COM PRODUCAO DE JINGLES, VINHETAS E S...",FINALÍSTICO
157,AGUA E ESGOTO - MULHERES ...,FINALÍSTICO
158,SEGURANCA E VIGILANCIA - MULHERES ...,FINALÍSTICO
159,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO

In [4]:
PARQUET_FILE_NAME = "receita.parquet"
df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/02-bronze/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,SG_PARTIDO,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,DT_RECEITA,DS_RECEITA,VR_RECEITA
0,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1475,#NULO#,05/08/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,2500
1,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1490,#NULO#,28/08/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,5000
2,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1506,#NULO#,01/10/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,2000
3,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1535,#NULO#,22/12/2025,TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MA...,4000
4,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,32206989000180,AGIR,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,#NULO#,#NULO#,25/04/2025,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,"1692,07"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194839,25/04/2026,16:27:11,4,Municipal,TO,9683,FÁTIMA,#NULO#,54775347000135,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194840,25/04/2026,16:27:11,4,Municipal,TO,9311,COLINAS DO TOCANTINS,#NULO#,53837785000118,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194841,25/04/2026,16:27:11,4,Municipal,TO,349,JUARINA,#NULO#,54427078000116,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194842,25/04/2026,16:27:11,4,Municipal,TO,9695,BERNARDO SAYÃO,#NULO#,54721419000161,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0
194843,25/04/2026,16:27:11,4,Municipal,TO,9483,NAZARÉ,#NULO#,55995337000178,UNIÃO,...,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,#NULO#,,#NULO#,0

## SILVER

### Receita

In [5]:
PARQUET_FILE_NAME = "receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,cd_tp_natureza_recurso,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio
0,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,NaN,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00,2025.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,NaN,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00,2025.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,NaN,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00,2025.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,NaN,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00,2025.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,NaN,NaN,NaN,32206989000180,AGIR,...,0,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,NaN,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194839,2026-04-25,16:27:11,4,MUNICIPAL,TO,9683,FATIMA,NaN,54775347000135,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194840,2026-04-25,16:27:11,4,MUNICIPAL,TO,9311,COLINAS DO TOCANTINS,NaN,53837785000118,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194841,2026-04-25,16:27:11,4,MUNICIPAL,TO,349,JUARINA,NaN,54427078000116,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194842,2026-04-25,16:27:11,4,MUNICIPAL,TO,9695,BERNARDO SAYAO,NaN,54721419000161,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN
194843,2026-04-25,16:27:11,4,MUNICIPAL,TO,9483,NAZARE,NaN,55995337000178,UNIAO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.00,NaN

In [ ]:
PARQUET_FILE_NAME = "receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
         sg_uf_doador,
        count(*)
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    GROUP BY sg_uf_doador
    """
).df()

#df.head()

df

   sg_uf_doador  count_star()
0            BA          3577
1            ES           598
2            PB           732
3            AL           354
4            MT           429
5            SP         16258
6            TO           486
7            BR        114957
8            PA          1433
9            SC          4793
10           MA           752
11           MG          2141
12          NaN          6419
13           DF          1869
14           AP          1183
15           PI          2588
16           PR          1602
17           RJ          2872
18           RN           519
19           SE           416
20           PE          1885
21           CE          1575
22           RO           755
23           RR           434
24           AC           399
25           GO           505
26           RS         24030
27           AM           463
28           MS           820

In [13]:
PARQUET_FILE_NAME = "receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
         ds_tp_origem_doacao,
        count(*)
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    GROUP BY ds_tp_origem_doacao
    """
).df()

#df.head()

df

              ds_tp_origem_doacao  count_star()
0                             NaN          6419
1       COTAS DO FUNDO PARTIDARIO           408
2   RECURSOS DE PESSOAS JURIDICAS          1222
3     RECURSOS DE PESSOAS FISICAS        169484
4          RECURSOS DE CANDIDATOS           382
5  RECURSOS DE PARTIDOS POLITICOS         16465
6         ORIGEM NAO IDENTIFICADA           464

In [7]:
PARQUET_FILE_NAME = "receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
         ds_receita,
        count(*)
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    GROUP BY ds_receita
    """
).df()

#df.head()

df

                                           ds_receita  count_star()
0                   GANHOS COM ATIVOS - OUTROS GANHOS            10
1   JUROS E OUTRAS RENDAS - RENDIMENTOS DE APLICAC...          3050
2   TRANSFERENCIAS INTRAPARTIDARIAS DE RECURSOS ES...           326
3   OUTRAS RECEITAS DIVERSAS - RECEITAS COM EVENTO...          1580
4   DOACOES PARA MANUTENCAO DO PARTIDO - PESSOAS F...           736
5   TRANSFERENCIAS INTRAPARTIDARIAS DE ATIVO IMOBI...            25
6   TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...           513
7          REEMBOLSO DE OUTROS ADIANTAMENTOS DIVERSOS            22
8                CONTRIBUICOES - OUTRAS CONTRIBUICOES         40341
9           REEMBOLSO DE ADIANTAMENTOS A FORNECEDORES            99
10  OUTRAS RECEITAS DIVERSAS - OUTRAS RECEITAS DIV...           715
11           GANHOS COM ATIVOS - VENDA DE PUBLICACOES             1
12  TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...         13734
13  TRANSFERENCIAS INTRAPARTIDARIAS DE RECURSOS ES...            10
14  SOBRAS FINANCEIRAS DE CAMPANHA - PARTIDOS POLI...            12
15  FUNDO PARTIDARIO - DIRECAO NACIONAL - COTAS RE...           408
16  SOBRAS FINANCEIRAS NAO UTILIZADAS PELA FUNDACA...             7
17  TRANSFERENCIAS INTRAPARTIDARIAS DE RECURSOS ES...           594
18  OBTENCAO DE RECURSOS POR MEIO DE EMPRESTIMOS B...             1
19          JUROS E OUTRAS RENDAS - DESCONTOS OBTIDOS           576
20  DOACOES PARA MANUTENCAO DO PARTIDO - FINANCIAM...           202
21  GANHOS COM ATIVOS - VALOR DE VENDA NA ALIENACA...            12
22                                                NaN          2793
23        SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS           379
24                       GANHOS COM ATIVOS - ALUGUEIS            48
25  GANHOS COM ATIVOS - VENDA DE MATERIAIS DE DIVU...          1275
26  PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREG...             1
27  DOACOES PARA CAMPANHAS ELEITORAIS - PESSOAS FI...           192
28  TRANSFERENCIAS INTRAPARTIDARIAS DE ATIVO IMOBI...            14
29                RECURSOS DE ORIGEM NAO IDENTIFICADA           464
30                        CONTRIBUICOES - DE FILIADOS         98436
31               RECURSOS RECEBIDOS DE FONTES VEDADAS           180
32  PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREG...             2
33  RECUPERACAO DE DEPOSITOS RESTITUIVEIS E VALORE...            33
34  PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREG...             1
35  JUROS E OUTRAS RENDAS - OUTRAS RECEITAS FINANC...           235
36                   CONTRIBUICOES - DE PARLAMENTARES          9660
37  DOACOES/TRANSFERENCIAS PARA CAMPANHAS ELEITORA...            46
38  DOACOES/TRANSFERENCIAS PARA CAMPANHAS ELEITORA...            24
39  RECUPERACAO DE DEPOSITOS RESTITUIVEIS E VALORE...           287
40  TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...           889
41  DOACOES PARA MANUTENCAO DO PARTIDO - PESSOAS F...         16904
42  TRANSPORTES E VIAGENS - REEEMBOLSO DE ADIANTAM...             7

### Despesa

In [14]:
PARQUET_FILE_NAME = "despesa.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,NaN,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
1,2026-04-25,16:26:12,2025,NaN,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
2,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,CE,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
3,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,MS,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
4,2026-04-25,16:26:12,2025,NaN,2,ESTADUAL,SP,-1,NaN,-1,...,NaN,NaN,NaN,NaT,0.0,0.00,0.00,-1,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196028,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-10-31,0.0,806.61,4598.72,1,FUNDO PARTIDARIO,4052151
196029,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,00360305000104,CAIXA ECONOMICA FEDERAL - CEF,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-02-28,0.0,25.05,455.91,1,FUNDO PARTIDARIO,4050872
196030,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-04-30,0.0,107.70,1960.92,1,FUNDO PARTIDARIO,4051614
196031,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-09-30,0.0,455.45,3297.81,1,FUNDO PARTIDARIO,4052150
196032,2026-04-25,16:23:25,2025,O,3,ZONAL,DF,-1,NaN,9,...,29979036000140,INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-05-31,0.0,5.12,1609.03,1,FUNDO PARTIDARIO,4051786

In [15]:
PARQUET_FILE_NAME = "despesa.parquet"

df = duckdb.sql(
    f"""
    SELECT
        tp_despesa,
        count(*)
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    GROUP BY tp_despesa
    """
).df()

#df.head()

df

  tp_despesa  count_star()
0          D         28083
1          G        163381
2          O          1221
3        NaN          2793
4          A           555

In [26]:
PARQUET_FILE_NAME = "classificacao_despesa.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/03-silver/{PARQUET_FILE_NAME}'
    )
    """
).df()

#df.head()

df

                                            nm_despesa        tp_gasto
0    DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...  ADMINISTRATIVO
1    TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
2    TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...  ADMINISTRATIVO
3    TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
4    TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...     FINALÍSTICO
..                                                 ...             ...
155  SEGURANCA E VIGILANCIA - DESPESAS ELEITORAIS  ...     FINALÍSTICO
156  DESPESAS COM PRODUCAO DE JINGLES, VINHETAS E S...     FINALÍSTICO
157  AGUA E ESGOTO - MULHERES                      ...     FINALÍSTICO
158  SEGURANCA E VIGILANCIA - MULHERES             ...     FINALÍSTICO
159  DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...  ADMINISTRATIVO

[160 rows x 2 columns]

## GOLD

In [17]:
PARQUET_FILE_NAME = "partido_ano_receita.parquet"

df = duckdb.sql(
    f"""
    SELECT
        *
    FROM read_parquet(
        '../data/04-gold/{PARQUET_FILE_NAME}'
    )
    """
).df()

df

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AGIR,2025,1.207855e+06,0.000000e+00,716425.63,4.679866e+05,56,0.000000,59.313878,2.156884e+04
1,AVANTE,2025,5.362063e+07,2.944308e+07,260244.61,1.169648e+07,41,54.909980,0.485344,1.307820e+06
2,CIDADANIA,2025,1.175145e+07,3.815505e+06,501646.01,7.429742e+06,79,32.468366,4.268799,1.487526e+05
3,DC,2025,3.523606e+06,0.000000e+00,1281392.84,2.234785e+06,150,0.000000,36.365949,2.349071e+04
4,DEM,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
5,DEMOCRATA,2025,7.200533e+04,0.000000e+00,31680.33,4.032000e+04,8,0.000000,43.997201,9.000666e+03
6,MDB,2025,2.193936e+08,8.890063e+07,2987303.92,1.214328e+08,1179,40.521068,1.361618,1.860845e+05
7,MOBILIZA,2025,1.089512e+06,0.000000e+00,129433.75,6.500000e+05,60,0.000000,11.879975,1.815853e+04
8,NOVO,2025,9.498010e+07,0.000000e+00,2402801.33,4.681508e+07,10192,0.000000,2.529795,9.319083e+03
9,PATRIOTA,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
10,PC DO B,2025,3.331525e+07,1.982971e+07,3480874.39,9.982024e+06,2145,59.521410,10.448290,1.553159e+04
11,PCB,2025,7.244960e+04,0.000000e+00,64013.48,8.000000e+02,67,0.000000,88.355878,1.081337e+03
12,PCO,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
13,PDT,2025,1.204480e+08,4.442062e+07,1223025.10,3.516317e+07,825,36.879487,1.015396,1.459976e+05
14,PL,2025,4.354022e+08,2.086250e+08,40965912.74,1.419754e+08,741,47.915465,9.408751,5.875874e+05
15,PODE,2025,1.072410e+08,5.878967e+07,2129297.21,4.629979e+07,529,54.820145,1.985525,2.027240e+05
16,PP,2025,1.606949e+08,5.680477e+07,3478597.68,8.376226e+07,1437,35.349449,2.164722,1.118267e+05
17,PRD,2025,1.048771e+08,3.374260e+07,299336.95,7.039642e+07,107,32.173480,0.285417,9.801595e+05
18,PRTB,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
19,PSB,2025,8.264136e+07,5.370288e+07,2027596.67,2.402719e+07,692,64.983059,2.453489,1.194239e+05
20,PSC,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
21,PSD,2025,2.469565e+08,9.135067e+07,1331629.89,1.352106e+08,688,36.990593,0.539216,3.589484e+05
22,PSDB,2025,6.742977e+07,2.963210e+07,5045004.33,3.111011e+07,788,43.945131,7.481865,8.557078e+04
23,PSL,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
24,PSOL,2025,2.431282e+08,2.090511e+08,685627.79,3.338911e+07,127,85.983917,0.282003,1.914395e+06
25,PSTU,2025,1.399686e+06,0.000000e+00,1305280.58,9.440548e+04,387,0.000000,93.255239,3.616760e+03
26,PT,2025,3.664338e+08,1.529199e+08,33868524.01,1.792951e+08,26006,41.731939,9.242741,1.409036e+04
27,PTB,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
28,PV,2025,1.855967e+07,1.287004e+07,371364.53,5.286500e+06,202,69.344102,2.000922,9.187958e+04
29,REDE,2025,1.555933e+07,1.333218e+07,180451.15,2.034034e+06,588,85.686113,1.159762,2.646144e+04
30,REPUBLICANOS,2025,2.073313e+08,9.639831e+07,4479893.25,6.013558e+07,1874,46.494811,2.160741,1.106357e+05
31,SDD,2025,5.249612e+07,1.938335e+07,2217393.08,2.975792e+07,82,36.923395,4.223918,6.401965e+05
32,UNIAO,2025,1.642331e+08,0.000000e+00,558854.50,1.626579e+08,334,0.000000,0.340281,4.917158e+05
33,UP,2025,6.243870e+03,0.000000e+00,6243.87,0.000000e+00,37,0.000000,100.000000,1.687532e+02

In [25]:
from IPython.display import display
import duckdb

for file in PARQUET_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        LIMIT 100
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    display(df.head())

Arquivo: ../data/04-gold/despesa_enriquecida.parquet

Shape: (100, 41)

Colunas:
dt_geracao                   datetime64[us]
hh_geracao                              str
aa_exercicio                          int64
tp_despesa                           object
cd_tp_esfera_partidaria                 str
ds_tp_esfera_partidaria                 str
sg_uf                                   str
cd_municipio                            str
nm_municipio                            str
nr_zona                               int64
cd_cnpj_prestador_conta                 str
sg_partido                              str
nm_partido                              str
cd_tp_documento                      object
ds_tp_documento                      object
nr_documento                         object
aa_aidf                               int64
nr_aidf                                 str
cd_tp_fornecedor                     object
ds_tp_fornecedor                     object
cd_cpf_cnpj_fornecedor               object
nm_fornecedor                        object
ds_gasto                                str
dt_pagamento                 datetime64[us]
vl_gasto                            float64
vl_pagamento                        float64
vl_documento                        float64
cd_fonte_despesa                        str
ds_fonte_despesa                     object
sq_despesa                            int64
nm_razao_social                      object
nm_fantasia                          object
is_cnpj_enriquecido                    bool
tp_gasto                                str
tp_classificacao_origem                 str
in_despesa_administrativa              bool
in_despesa_finalistica                 bool
in_despesa_indefinida                  bool
vl_despesa_administrativa           float64
vl_despesa_finalistica              float64
vl_despesa_indefinida               float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nm_fantasia,is_cnpj_enriquecido,tp_gasto,tp_classificacao_origem,in_despesa_administrativa,in_despesa_finalistica,in_despesa_indefinida,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida
0,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
1,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
2,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
3,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
4,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0

Arquivo: ../data/04-gold/partido_ano_despesa.parquet

Shape: (34, 11)

Colunas:
sg_partido                        str
aa_exercicio                    int64
vl_despesa_total              float64
vl_despesa_administrativa     float64
vl_despesa_finalistica        float64
vl_despesa_indefinida         float64
qtd_fornecedores_unicos         int64
pct_despesa_administrativa    float64
pct_despesa_finalistica       float64
pct_despesa_indefinida        float64
ticket_medio_despesa          float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_despesa_total,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida,qtd_fornecedores_unicos,pct_despesa_administrativa,pct_despesa_finalistica,pct_despesa_indefinida,ticket_medio_despesa
0,AGIR,2025,873771.32,685084.32,0.0,188687.00,37,78.405448,0.0,21.594552,23615.441081
1,AVANTE,2025,21884602.24,9806307.71,0.0,4566747.76,277,44.809166,0.0,20.867401,79005.784260
2,CIDADANIA,2025,4106777.89,2814476.88,0.0,827583.21,288,68.532484,0.0,20.151643,14259.645451
3,DC,2025,1954621.90,1344255.70,0.0,609566.20,94,68.773183,0.0,31.185888,20793.850000
4,DEM,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN

Arquivo: ../data/04-gold/partido_ano_receita.parquet

Shape: (34, 10)

Colunas:
sg_partido                   str
aa_exercicio               int64
vl_receita_total         float64
vl_receita_publica       float64
vl_receita_privada       float64
vl_receita_partidaria    float64
qtd_doadores_unicos        int64
pct_receita_publica      float64
pct_receita_privada      float64
ticket_medio_receita     float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AGIR,2025,1207854.99,0.00,716425.63,467986.60,56,0.000000,59.313878,2.156884e+04
1,AVANTE,2025,53620628.37,29443076.52,260244.61,11696480.12,41,54.909980,0.485344,1.307820e+06
2,CIDADANIA,2025,11751454.30,3815505.23,501646.01,7429741.60,79,32.468366,4.268799,1.487526e+05
3,DC,2025,3523606.22,0.00,1281392.84,2234784.96,150,0.000000,36.365949,2.349071e+04
4,DEM,2025,0.00,0.00,0.00,0.00,0,NaN,NaN,NaN

Arquivo: ../data/04-gold/receita_enriquecida.parquet

Shape: (100, 48)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                              object
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
nm_razao_social                              str
nm_fantasia                                  str
is_cnpj_enriquecido                         bool
tp_receita                                   str
in_receita_publica                          bool
in_receita_privada                          bool
in_receita_partidaria                       bool
vl_receita_publica                       float64
vl_receita_privada                       float64
vl_receita_partidaria                    float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,5000.0

In [ ]:
for file in PARQUET_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    print(df.head())