# Verificação rápida dos dados

In [11]:
from IPython.display import display
import duckdb
import pandas as pd
import os

PARQUET_BRONZE_DIR = "../data/02-bronze"
PARQUET_SILVER_DIR = "../data/03-silver"
PARQUET_GOLD_DIR = "../data/04-gold"

OUTPUT_DIR = "../data/05-output/notebooks"

## Funções auxiliares

In [36]:
# =========================================================
# 1. Leitura
# =========================================================

def get_parquet_files(dir_path):
    """Retorna uma lista de arquivos Parquet em um diretório específico."""

    if not os.path.exists(dir_path):
        return []

    return [
        os.path.join(dir_path, x)
        for x in os.listdir(dir_path)
        if x.endswith(".parquet")
    ]

def load_parquet_dataset(file_path, sample_size=10):

    df_full = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file_path}')
        """
    ).df()

    df_sample = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file_path}')
        USING SAMPLE {sample_size} ROWS
        """
    ).df()

    return {
        "file_path": file_path,
        "file_name": os.path.basename(file_path),
        "df_full": df_full,
        "df_sample": df_sample
    }


# =========================================================
# 2. Profiling / Estatísticas
# =========================================================

def generate_profile(dataset):

    df = dataset["df_full"]

    profile = {
        "shape": df.shape,
        "columns": [],
        "numeric_stats": None,
        "categorical_summary": None,
        "categorical_details": None
    }

    # =====================================================
    # Colunas
    # =====================================================

    for col in df.columns:

        null_count = df[col].isnull().sum()

        profile["columns"].append({
            "column": col,
            "dtype": str(df[col].dtype),
            "null_count": int(null_count),
            "null_percent": round(
                (null_count / len(df)) * 100,
                2
            )
        })

    # =====================================================
    # Numéricas
    # =====================================================

    df_numeric = df.select_dtypes(include=["number"])

    if not df_numeric.empty:

        numeric_stats = df_numeric.describe().T

        numeric_stats["null_count"] = (
            df_numeric.isnull().sum()
        )

        numeric_stats["null_percent"] = (
            df_numeric.isnull().sum() / len(df)
        ) * 100

        profile["numeric_stats"] = numeric_stats

    # =====================================================
    # Categóricas
    # =====================================================

    df_cat = df.select_dtypes(
        include=["object", "category", "string"]
    )

    if not df_cat.empty:

        # =================================================
        # Resumo geral das colunas categóricas
        # =================================================

        categorical_summary = []

        # =================================================
        # Detalhamento dos valores
        # =================================================

        categorical_details = []

        for col in df_cat.columns:

            null_count = df_cat[col].isnull().sum()

            # =============================================
            # Resumo
            # =============================================

            categorical_summary.append({

                "column": col,

                "dtype": str(df_cat[col].dtype),

                "null_count": int(null_count),

                "null_percent": round(
                    (null_count / len(df)) * 100,
                    2
                ),

                "unique_values": int(
                    df_cat[col].nunique(dropna=False)
                )
            })

            # =============================================
            # Top 10 valores
            # =============================================

            value_counts = (
                df_cat[col]
                .value_counts(dropna=False)
                .head(10)
            )

            for value, count in value_counts.items():

                percent = (count / len(df)) * 100

                categorical_details.append({

                    "column": col,

                    "value": str(value),

                    "count": int(count),

                    "percent": round(percent, 2)
                })

        profile["categorical_summary"] = pd.DataFrame(
            categorical_summary
        )

        profile["categorical_details"] = pd.DataFrame(
            categorical_details
        )

    return profile

# =========================================================
# 3. Visualização
# =========================================================

def display_profile(dataset, profile):

    print(f"\nArquivo: {dataset['file_name']}")

    print("\nShape:")
    print(profile["shape"])

    print("\nAmostra:")
    display(dataset["df_sample"])

    if profile["numeric_stats"] is not None:

        print("\nEstatísticas Numéricas")
        display(profile["numeric_stats"])

    if profile["categorical_summary"] is not None:

        print("\nResumo categórico")
        display(profile["categorical_summary"])

    if profile["categorical_details"] is not None:

        print("\nTop valores categóricos")
        display(profile["categorical_details"])

        

# =========================================================
# 4. Persistência
# =========================================================

def save_profile_txt(dataset, profile, output_dir, camada):

    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(
        output_dir,
        f"{camada}_{dataset['file_name'].replace('.parquet', '.txt')}"
    )

    with open(output_file, "w", encoding="utf-8") as f:

        f.write("=" * 100 + "\n")
        f.write(f"ARQUIVO: {dataset['file_name']}\n")
        f.write("=" * 100 + "\n\n")

        # =================================================
        # Shape
        # =================================================

        f.write("SHAPE\n")
        f.write("-" * 100 + "\n")
        f.write(f"{profile['shape']}\n\n")

        # =================================================
        # Colunas
        # =================================================

        f.write("COLUNAS\n")
        f.write("-" * 100 + "\n")

        for col in profile["columns"]:

            f.write(
                f"{col['column']:<30} | "
                f"{col['dtype']:<15} | "
                f"Nulos: {col['null_count']:<10} | "
                f"% Null: {col['null_percent']:>6.2f}%\n"
            )

        # =================================================
        # Estatísticas numéricas
        # =================================================

        if profile["numeric_stats"] is not None:

            f.write("\n\nESTATÍSTICAS NUMÉRICAS\n")
            f.write("-" * 100 + "\n")

            f.write(
                profile["numeric_stats"].to_string()
            )

        # =================================================
        # Resumo categórico
        # =================================================

        if profile["categorical_summary"] is not None:

            f.write("\n\nRESUMO CATEGÓRICO\n")
            f.write("-" * 100 + "\n")

            f.write(
                profile["categorical_summary"].to_string(
                    index=False
                )
            )

        # =================================================
        # Detalhamento categórico
        # =================================================

        if profile["categorical_details"] is not None:

            f.write("\n\nTOP VALORES CATEGÓRICOS\n")
            f.write("-" * 100 + "\n")

            f.write(
                profile["categorical_details"].to_string(
                    index=False
                )
            )

        # =================================================
        # Sample
        # =================================================

        f.write("\n\nAMOSTRA\n")
        f.write("-" * 100 + "\n")

        f.write(
            dataset["df_sample"].to_string(index=False)
        )

    print(f"Arquivo salvo: {output_file}")

# =========================================================
# Pipeline de análise
# =========================================================

def process_layer(layer_name, layer_dir, output_dir):

    print(
        "\n",
        "=" * 50,
        f"\n\t Verificando arquivos {layer_name.upper()} \n",
        "=" * 50
    )

    files = get_parquet_files(layer_dir)

    if not files:
        print(f"Nenhum arquivo encontrado em: {layer_dir}")
        return

    for file in files:

        try:

            dataset = load_parquet_dataset(file)

            profile = generate_profile(dataset)

            display_profile(dataset, profile)

            save_profile_txt(
                dataset=dataset,
                profile=profile,
                output_dir=output_dir,
                camada=layer_name
            )

        except Exception as e:

            print(f"Erro ao processar {file}")
            print(f"Detalhes: {e}")

## Visualiza todos os dados

In [37]:
# =========================================================
# Execução
# =========================================================

LAYERS = {
    "02-bronze": PARQUET_BRONZE_DIR,
    "03-silver": PARQUET_SILVER_DIR,
    "04-gold": PARQUET_GOLD_DIR
}

for layer_name, layer_dir in LAYERS.items():

    process_layer(
        layer_name=layer_name,
        layer_dir=layer_dir,
        output_dir=OUTPUT_DIR
    )

 ==================================================
	 Verificando arquivos 02-BRONZE
 ==================================================

Arquivo: despesa.parquet

Shape:
(196033, 30)

Amostra:

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,DS_GASTO,DT_PAGAMENTO,VR_GASTO,VR_PAGAMENTO,VR_DOCUMENTO,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:23:25,2025,A,4,Municipal,ES,5699,SERRA,-1,...,#NULO#,#NULO#,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,05/06/2025,0,",07",",07",2,Outros Recursos,-1
1,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,04566311000173,Direção Municipal/Comissão Provisória - PT - R...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,31/10/2025,"411,03","411,03","411,03",2,Outros Recursos,-1
2,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,15893910000118,Direção Municipal/Comissão Provisória - PT - V...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,23/05/2025,68,68,68,2,Outros Recursos,-1
3,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,01216789000185,Direção Municipal/Comissão Provisória - PT - B...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,19/05/2025,"2804,91","2804,91","2804,91",2,Outros Recursos,-1
4,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,51927036000156,Direção Municipal/Comissão Provisória - PT - S...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,25/03/2025,"63,17","63,17","63,17",2,Outros Recursos,-1
5,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,73739724000125,Direção Municipal/Comissão Provisória - PT - C...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,09/05/2025,"586,71","586,71","586,71",2,Outros Recursos,-1
6,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,14567904000108,Direção Estadual/Distrital - PSD - SÃO PAULO,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - FUNDO P...,03/04/2025,750000,750000,750000,1,Fundo Partidário,-1
7,25/04/2026,16:23:25,2025,G,1,Distrital,DF,-1,#NULO#,-1,...,01194020000103,CONDOMINIO DO EDIFICIO CENTRAL PARK,ALUGUÉIS E CONDOMÍNIOS - TAXAS DE CONDOMÍNIOS ...,26/02/2025,"193,26","193,26","193,26",1,Fundo Partidário,4016410
8,25/04/2026,16:23:25,2025,G,2,Estadual,SP,-1,#NULO#,-1,...,04331943000158,AZR SERVICOS LTDA,SEGURANÇA E VIGILÂNCIA - ORDINÁRIAS,20/10/2025,"305,91","305,91","305,91",1,Fundo Partidário,3985282
9,25/04/2026,16:23:25,2025,G,2,Estadual,CE,-1,#NULO#,-1,...,06887668002203,SUPERMERCADO COMETA LTDA,MATERIAL DE CONSUMO - MATERIAIS DE EXPEDIENTE ...,08/08/2025,"94,27","94,27","94,27",1,Fundo Partidário,4059488

Resumo categórico

                     column dtype  null_count  null_percent  unique_values
0                DT_GERACAO   str           0           0.0              1
1                HH_GERACAO   str           0           0.0              2
2              AA_EXERCICIO   str           0           0.0              1
3                TP_DESPESA   str           0           0.0              5
4   CD_TP_ESFERA_PARTIDARIA   str           0           0.0              5
5   DS_TP_ESFERA_PARTIDARIA   str           0           0.0              5
6                     SG_UF   str           0           0.0             28
7              CD_MUNICIPIO   str           0           0.0           2053
8              NM_MUNICIPIO   str           0           0.0           2015
9                   NR_ZONA   str           0           0.0              2
10  NR_CNPJ_PRESTADOR_CONTA   str           0           0.0           3930
11               SG_PARTIDO   str           0           0.0             34
12               NM_PARTIDO   str           0           0.0             34
13          CD_TP_DOCUMENTO   str           0           0.0              7
14          DS_TP_DOCUMENTO   str           0           0.0              7
15             NR_DOCUMENTO   str           0           0.0          70836
16                  AA_AIDF   str           0           0.0             16
17                  NR_AIDF   str           0           0.0            250
18         CD_TP_FORNECEDOR   str           0           0.0              3
19         DS_TP_FORNECEDOR   str           0           0.0              3
20   NR_CPF_CNPJ_FORNECEDOR   str           0           0.0          17719
21            NM_FORNECEDOR   str           0           0.0          19535
22                 DS_GASTO   str           0           0.0            252
23             DT_PAGAMENTO   str           0           0.0            383
24                 VR_GASTO   str           0           0.0          61060
25             VR_PAGAMENTO   str           0           0.0          61687
26             VR_DOCUMENTO   str           0           0.0          59257
27         CD_FONTE_DESPESA   str           0           0.0              5
28         DS_FONTE_DESPESA   str           0           0.0              5
29               SQ_DESPESA   str           0           0.0         154899

Top valores categóricos

           column       value   count  percent
0      DT_GERACAO  25/04/2026  196033   100.00
1      HH_GERACAO    16:23:25  193240    98.58
2      HH_GERACAO    16:26:12    2793     1.42
3    AA_EXERCICIO        2025  196033   100.00
4      TP_DESPESA           G  163381    83.34
..            ...         ...     ...      ...
216    SQ_DESPESA     3970176      22     0.01
217    SQ_DESPESA     4019451      22     0.01
218    SQ_DESPESA     4001951      22     0.01
219    SQ_DESPESA     3896621      20     0.01
220    SQ_DESPESA     3657768      20     0.01

[221 rows x 4 columns]

Arquivo salvo: ../data/05-output/notebooks/02-bronze_despesa.txt

Arquivo: classificacao_despesa.parquet

Shape:
(160, 2)

Amostra:

,DESPESA,CLASSIFICACAO
0,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,FINALÍSTICO
1,ALUGUEIS E CONDOMINIOS - LOCACAO DE BENS MOVEI...,ADMINISTRATIVO
2,PESSOAL - PIS SOBRE FOLHA DE PAGAMENTO - ORDIN...,ADMINISTRATIVO
3,SERVICOS TECNICO-PROFISSIONAIS - SERVICOS DE I...,ADMINISTRATIVO
4,DESPESAS COM CRIACAO E INCLUSAO DE PAGINAS INS...,FINALÍSTICO
5,PESQUISAS E TESTES DE OPINIAO PUBLICA - ORDINA...,FINALÍSTICO
6,MATERIAL DE CONSUMO - MATERIAIS DE COPA E COZI...,FINALÍSTICO
7,PESQUISAS E TESTES DE OPINIAO PUBLICA - MULHER...,FINALÍSTICO
8,LANCHES E REFEICOES - DESPESAS ELEITORAIS ...,FINALÍSTICO
9,"DESPESAS COM PRODUCAO DE JINGLES, VINHETAS E S...",FINALÍSTICO

Resumo categórico

,column,dtype,null_count,null_percent,unique_values
0,DESPESA ...,str,0,0.0,160
1,CLASSIFICACAO,str,0,0.0,3

Top valores categóricos

,column,value,count,percent
0,DESPESA ...,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,1,0.62
1,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
2,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
3,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
4,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
5,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
6,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
7,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
8,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
9,DESPESA ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
10,CLASSIFICACAO,FINALÍSTICO,85,53.12
11,CLASSIFICACAO,ADMINISTRATIVO,58,36.25
12,CLASSIFICACAO,INDEFINIDO,17,10.62

Arquivo salvo: ../data/05-output/notebooks/02-bronze_classificacao_despesa.txt

Arquivo: receita.parquet

Shape:
(194844, 36)

Amostra:

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,SG_PARTIDO,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,DT_RECEITA,DS_RECEITA,VR_RECEITA
0,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676213000138,MDB,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,3984,#NULO#,26/09/2025,CONTRIBUIÇÕES - DE PARLAMENTARES,1000
1,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1017596,1017596,03/01/2025,CONTRIBUIÇÕES - DE FILIADOS,"39,75"
2,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1018055,1018055,03/01/2025,CONTRIBUIÇÕES - DE FILIADOS,40
3,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1018273,1018273,03/01/2025,CONTRIBUIÇÕES - DE FILIADOS,"39,75"
4,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1031806,1031806,11/03/2025,CONTRIBUIÇÕES - DE FILIADOS,"39,75"
5,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1037225,1037225,31/03/2025,CONTRIBUIÇÕES - DE FILIADOS,50
6,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1036287,1036287,11/03/2025,CONTRIBUIÇÕES - DE FILIADOS,50
7,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1038536,#NULO#,14/10/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,"1029,02"
8,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1011069,#NULO#,03/06/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,"47,43"
9,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1017634,#NULO#,02/07/2025,CONTRIBUIÇÕES - DE PARLAMENTARES,"1697,05"

Resumo categórico

,column,dtype,null_count,null_percent,unique_values
0,DT_GERACAO,str,0,0.0,1
1,HH_GERACAO,str,0,0.0,2
2,CD_TP_ESFERA_PARTIDARIA,str,0,0.0,5
3,DS_TP_ESPERA_PARTIDARIA,str,0,0.0,5
4,SG_UF,str,0,0.0,28
5,CD_MUNICIPIO,str,0,0.0,2103
6,NM_MUNICIPIO,str,0,0.0,2065
7,NR_ZONA,str,0,0.0,3
8,NR_CNPJ_PRESTADOR_CONTA,str,0,0.0,4134
9,SG_PARTIDO,str,0,0.0,34
10,NM_PARTIDO,str,0,0.0,34
11,CD_TP_ORIGEM_DOACAO,str,0,0.0,7
12,DS_TP_ORIGEM_DOACAO,str,0,0.0,7
13,NR_CPF_CNPJ_DOADOR,str,0,0.0,49264
14,NM_DOADOR,str,0,0.0,50253
15,CD_TP_ESFERA_PARTIDARIA_DOADOR,str,0,0.0,6
16,DS_TP_ESFERA_PARTIDARIA_DOADOR,str,0,0.0,6
17,SG_UF_DOADOR,str,0,0.0,29
18,CD_MUNICIPIO_DOADOR,str,0,0.0,545
19,NM_MUNICIPIO_DOADOR,str,0,0.0,543
20,NR_ZONA_DOADOR,str,0,0.0,1
21,SQ_CANDIDATO_DOADOR,str,0,0.0,352
22,NR_CANDIDATO_DOADOR,str,0,0.0,226
23,CD_CANDIDATO_CARGO_DOADOR,str,0,0.0,6
24,DS_CANDIDATO_CARGO_DOADOR,str,0,0.0,6
25,CD_TP_FONTE_RECURSO,str,0,0.0,5
26,DS_TP_FONTE_RECURSO,str,0,0.0,9
27,CD_TP_NATUREZA_RECURSO,str,0,0.0,3
28,DS_TP_NATUREZA_RECURSO,str,0,0.0,3
29,CD_TP_ESPECIE_RECURSO,str,0,0.0,8
30,DS_TP_ESPECIE_RECURSO,str,0,0.0,8
31,NR_RECIBO_DOACAO,str,0,0.0,98882
32,NR_DOCUMENTO,str,0,0.0,26338
33,DT_RECEITA,str,0,0.0,354
34,DS_RECEITA,str,0,0.0,43
35,VR_RECEITA,str,0,0.0,23033

Top valores categóricos

                      column       value   count  percent
0                 DT_GERACAO  25/04/2026  194844   100.00
1                 HH_GERACAO    16:24:44  192051    98.57
2                 HH_GERACAO    16:27:11    2793     1.43
3    CD_TP_ESFERA_PARTIDARIA           0  115530    59.29
4    CD_TP_ESFERA_PARTIDARIA           4   46431    23.83
..                       ...         ...     ...      ...
266               VR_RECEITA          15    4849     2.49
267               VR_RECEITA          20    3329     1.71
268               VR_RECEITA           0    2793     1.43
269               VR_RECEITA         200    2771     1.42
270               VR_RECEITA          60    2731     1.40

[271 rows x 4 columns]

Arquivo salvo: ../data/05-output/notebooks/02-bronze_receita.txt

Arquivo: cnpj.parquet

Shape:
(14879, 28)

Amostra:

,cd_cnpj,nm_empresarial,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,1720480000128,FLORICULTURA FLORESTA FLORES LTDA,FLORICULTURA FLORESTA FLORES,1997-03-24 00:00:00,DF,CENTRO-OESTE,Matriz,2005-09-03 00:00:00,Ativa,None,...,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,47,COMÉRCIO VAREJISTA,Comércio varejista de produtos novos não espec...,47.8,47.89-0,Comércio varejista de outros produtos novos nã...,47.89-0/02,Comércio varejista de plantas e flores naturais,2026-04-13 05:46:14.493801000
1,26787220000109,PONTUAL BRINDES E CONFECCOES LTDA,D' BRINDES,2017-01-03 00:00:00,DF,CENTRO-OESTE,Matriz,2017-01-03 00:00:00,Ativa,None,...,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,46,"COMÉRCIO POR ATACADO, EXCETO VEÍCULOS AUTOMOTO...",Comércio atacadista de produtos de consumo não...,46.4,46.47-8,Comércio atacadista de artigos de escritório e...,46.47-8/01,Comércio atacadista de artigos de escritório e...,2026-04-13 05:46:14.493801000
2,24261214000180,RECRUTAS EXPRESS TRANSPORTES RAPIDOS LTDA,RECRUTAS,2016-02-26 00:00:00,SP,SUDESTE,Matriz,2016-02-26 00:00:00,Ativa,None,...,"TRANSPORTE, ARMAZENAGEM E CORREIO",53,CORREIO E OUTRAS ATIVIDADES DE ENTREGA,Atividades de malote e de entrega,53.2,53.20-2,Atividades de malote e de entrega,53.20-2/01,Serviços de malote não realizados pelo Correio...,2026-04-13 05:46:14.493801000
3,31511797000115,TRANSBUS TRANSPORTES LTDA,TRANSBUS,2018-09-14 00:00:00,RS,SUL,Matriz,2018-09-14 00:00:00,Ativa,None,...,"TRANSPORTE, ARMAZENAGEM E CORREIO",49,TRANSPORTE TERRESTRE,Transporte rodoviário de passageiros,49.2,49.21-3,"Transporte rodoviário coletivo de passageiros,...",49.21-3/01,"Transporte rodoviário coletivo de passageiros,...",2026-04-13 05:46:14.493801000
4,29191825000112,AGUIAR & FARIAS ADVOGADOS ASSOCIADOS,NaN,2017-08-28 00:00:00,SE,NORDESTE,Matriz,2017-08-28 00:00:00,Ativa,None,...,"ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS",69,"ATIVIDADES JURÍDICAS, DE CONTABILIDADE E DE AU...",Atividades jurídicas,69.1,69.11-7,"Atividades jurídicas, exceto cartórios",69.11-7/01,Serviços advocatícios,2026-04-13 05:46:14.493801000
5,58512773000137,GRAFICA VISAO JUNDIAI LTDA,GRAFICA VISAO,1988-01-18 00:00:00,SP,SUDESTE,Matriz,2005-09-24 00:00:00,Ativa,None,...,INDÚSTRIAS DE TRANSFORMAÇÃO,18,IMPRESSÃO E REPRODUÇÃO DE GRAVAÇÕES,Atividade de impressão,18.1,18.13-0,Impressão de materiais para outros usos,18.13-0/99,Impressão de material para outros usos,2026-04-13 05:46:14.493801000
6,94552650000193,SANT'ANNA & VIDOR LTDA,DEGRADE ARTES GRAFICAS,1992-04-15 00:00:00,RS,SUL,Matriz,2005-07-09 00:00:00,Ativa,None,...,INDÚSTRIAS DE TRANSFORMAÇÃO,18,IMPRESSÃO E REPRODUÇÃO DE GRAVAÇÕES,Atividade de impressão,18.1,18.13-0,Impressão de materiais para outros usos,18.13-0/99,Impressão de material para outros usos,2026-04-13 05:46:14.493801000
7,51616365000186,PARTIDO DOS TRABALHADORES - PINDAMONHANGABA - ...,PT DIRETORIO MUNICIPAL EM PINDAMONHANGABA,1983-05-09 00:00:00,SP,SUDESTE,Matriz,2020-06-18 00:00:00,Ativa,None,...,OUTRAS ATIVIDADES DE SERVIÇOS,94,ATIVIDADES DE ORGANIZAÇÕES ASSOCIATIVAS,Atividades de organizações associativas não es...,94.9,94.92-8,Atividades de organizações políticas,94.92-8/00,Atividades de organizações políticas,2026-04-13 05:46:14.493801000
8,36308715000153,CLEILSON RODRIGUES DE SOUSA LOPES,J A FLORES,2020-02-10 00:00:00,DF,CENTRO-OESTE,Matriz,2020-02-10 00:00:00,Ativa,None,...,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,47,COMÉRCIO VAREJISTA,Comércio varejista de produtos novos não espec...,47.8,47.89-0,Comércio varejista de outros produtos novos nã...,47.89-0/02,Comércio varejista de plantas e flores naturais,2026-04-13 05:46:14.493801000
9,36174437000199,36.174.437 PEDRO MANICA,NaN,2020-01-29 00:00:00,RS,SUL,Matriz,2020-01-29 00:00:00,Ativa,None,...,OUTRAS ATIVIDADES DE SERVIÇOS,95,REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS DE INFO...,Reparação e manutenção de objetos e equipament...,95.2,95.29-1,Reparação e manutenção de objetos e equipament...,95.29-1/02,Chaveiros,2026-04-13 05:46:14.493801000

Resumo categórico

                     column dtype  null_count  null_percent  unique_values
0                   cd_cnpj   str           4          0.03          14876
1            nm_empresarial   str           4          0.03          13677
2               nm_fantasia   str        5607         37.68           8508
3               dt_abertura   str           4          0.03           7684
4                     ed_uf   str           4          0.03             28
5        nm_regiao_politica   str           4          0.03              6
6   nm_tipo_estabelecimento   str           4          0.03              3
7     dt_situacao_cadastral   str         229          1.54           4855
8     nm_situacao_cadastral   str           4          0.03              6
9           dt_sit_especial   str       14855         99.84             21
10     nm_situacao_especial   str       14855         99.84              4
11     cd_natureza_juridica   str           4          0.03             44
12     nm_natureza_juridica   str           4          0.03             44
13                 nm_porte   str           4          0.03              4
14        vl_capital_social   str           4          0.03           1344
15                  cd_cnae   str           4          0.03            550
16             in_principal   str           4          0.03              2
17          cd_nivel1_secao   str           4          0.03             21
18          nm_nivel1_secao   str           4          0.03             21
19        cd_nivel2_divisao   str           4          0.03             75
20        nm_nivel2_divisao   str           4          0.03             75
21          nm_nivel3_grupo   str           4          0.03            186
22          cd_nivel3_grupo   str           4          0.03            186
23         cd_nivel4_classe   str           4          0.03            351
24         nm_nivel4_classe   str           4          0.03            351
25      cd_nivel5_subclasse   str           4          0.03            550
26      nm_nivel5_subclasse   str           4          0.03            550
27    dt_atualizacao_pj_rfb   str           4          0.03              2

Top valores categóricos

,column,value,count,percent
0,cd_cnpj,nan,4,0.03
1,cd_cnpj,87537000130,1,0.01
2,cd_cnpj,124153000140,1,0.01
3,cd_cnpj,165731000197,1,0.01
4,cd_cnpj,370353000183,1,0.01
...,...,...,...,...
232,nm_nivel5_subclasse,Preparação de documentos e serviços especializ...,253,1.70
233,nm_nivel5_subclasse,"Bancos múltiplos, com carteira comercial",250,1.68
234,nm_nivel5_subclasse,"Serviços de organização de feiras, congressos,...",236,1.59
235,dt_atualizacao_pj_rfb,2026-04-13 05:46:14.493801000,14875,99.97
236,dt_atualizacao_pj_rfb,nan,4,0.03

Arquivo salvo: ../data/05-output/notebooks/02-bronze_cnpj.txt

 ==================================================
	 Verificando arquivos 03-SILVER
 ==================================================

Arquivo: despesa.parquet

Shape:
(196033, 30)

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,None,-1,...,04700855000186,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - S...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-05-12,10.47,10.47,10.47,2,OUTROS RECURSOS,-1
1,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,None,-1,...,07799998000185,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - L...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-07-28,19.69,19.69,19.69,2,OUTROS RECURSOS,-1
2,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,None,-1,...,15696570000135,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - P...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-02-06,119.63,119.63,119.63,2,OUTROS RECURSOS,-1
3,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,None,-1,...,79306908000188,DIRECAO ESTADUAL/DISTRITAL - PT - SANTA CATARINA,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-01-17,30.42,30.42,30.42,2,OUTROS RECURSOS,-1
4,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,None,-1,...,81183253000140,DIRECAO ESTADUAL/DISTRITAL - PSDB - PARANA,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,2025-04-07,4500.00,4500.00,4500.00,1,FUNDO PARTIDARIO,-1
5,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,None,-1,...,04972926000108,DIRECAO ESTADUAL/DISTRITAL - CIDADANIA - AMAPA,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,2025-01-31,5000.00,5000.00,5000.00,1,FUNDO PARTIDARIO,-1
6,2026-04-25,16:23:25,2025,G,1,DISTRITAL,DF,-1,None,-1,...,07522669000192,NEOENERGIA BRASILIA,ENERGIA ELETRICA - ORDINARIAS,2025-08-04,31.31,31.31,31.31,1,FUNDO PARTIDARIO,3932665
7,2026-04-25,16:23:25,2025,G,2,ESTADUAL,SE,-1,None,-1,...,00394460040950,MINISTERIO DA FAZENDA,DESPESAS FINANCEIRAS - JUROS E MULTAS,2025-04-17,1409.77,1409.77,1409.77,1,FUNDO PARTIDARIO,3946570
8,2026-04-25,16:23:25,2025,G,2,ESTADUAL,PR,-1,None,-1,...,12770424890,VALDENOR ALVES SILVA,MATERIAL DE CONSUMO - MATERIAIS DE COPA E COZI...,2025-04-28,200.00,200.00,200.00,1,FUNDO PARTIDARIO,3851174
9,2026-04-25,16:23:25,2025,G,2,ESTADUAL,MA,-1,None,-1,...,06274757000150,CAEMA,AGUA E ESGOTO - ORDINARIAS,2025-10-31,67.16,67.16,67.16,1,FUNDO PARTIDARIO,4041020

Estatísticas Numéricas

,count,mean,std,min,25%,50%,75%,max,null_count,null_percent
aa_exercicio,196033.0,2.025000e+03,0.000000e+00,2025.0,2025.00,2025.0,2025.00,2025.00,0,0.0
nr_zona,196033.0,-9.863288e-01,3.694935e-01,-1.0,-1.00,-1.0,-1.00,9.00,0,0.0
aa_aidf,196033.0,9.162771e+01,4.231725e+02,-1.0,-1.00,-1.0,-1.00,2026.00,0,0.0
vl_gasto,196033.0,6.197181e+03,5.038810e+04,0.0,48.00,400.0,2800.00,3821394.33,0,0.0
vl_pagamento,196033.0,6.045245e+03,4.937167e+04,0.0,50.00,400.0,2790.63,3821394.33,0,0.0
vl_documento,196033.0,7.493695e+03,5.567233e+04,0.0,61.53,500.0,3196.45,3821394.33,0,0.0
sq_despesa,196033.0,3.301462e+06,1.446773e+06,-1.0,3841858.00,3934621.0,3999146.00,4069608.00,0,0.0

Resumo categórico

                     column dtype  null_count  null_percent  unique_values
0                hh_geracao   str           0          0.00              2
1                tp_despesa   str        2793          1.42              5
2   cd_tp_esfera_partidaria   str           0          0.00              5
3   ds_tp_esfera_partidaria   str           0          0.00              5
4                     sg_uf   str           0          0.00             28
5              cd_municipio   str           0          0.00           2053
6              nm_municipio   str      166027         84.69           2014
7   cd_cnpj_prestador_conta   str           0          0.00           3930
8                sg_partido   str           0          0.00             34
9                nm_partido   str           0          0.00             34
10          cd_tp_documento   str       31431         16.03              7
11          ds_tp_documento   str       31431         16.03              7
12             nr_documento   str       47054         24.00          70772
13                  nr_aidf   str           0          0.00            250
14         cd_tp_fornecedor   str        3348          1.71              3
15         ds_tp_fornecedor   str        3348          1.71              3
16   cd_cpf_cnpj_fornecedor   str        3348          1.71          17719
17            nm_fornecedor   str        3348          1.71          18759
18                 ds_gasto   str        2793          1.42            252
19         cd_fonte_despesa   str           0          0.00              5
20         ds_fonte_despesa   str        2793          1.42              5

Top valores categóricos

,column,value,count,percent
0,hh_geracao,16:23:25,193240,98.58
1,hh_geracao,16:26:12,2793,1.42
2,tp_despesa,G,163381,83.34
3,tp_despesa,D,28083,14.33
4,tp_despesa,nan,2793,1.42
...,...,...,...,...
152,ds_fonte_despesa,FUNDO PARTIDARIO,130259,66.45
153,ds_fonte_despesa,OUTROS RECURSOS,62756,32.01
154,ds_fonte_despesa,nan,2793,1.42
155,ds_fonte_despesa,RECURSOS PARA CAMPANHA,208,0.11
156,ds_fonte_despesa,FUNDO ESPECIAL DE FINANCIAMENTO DE CAMPANHA,17,0.01

Arquivo salvo: ../data/05-output/notebooks/03-silver_despesa.txt

Arquivo: classificacao_despesa.parquet

Shape:
(160, 2)

Amostra:

                                          nm_despesa        tp_gasto
0  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
1  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...     FINALÍSTICO
2  MATERIAL DE CONSUMO - MATERIAIS IMPRESSOS - OR...      INDEFINIDO
3  RADIO E TELEVISAO - ORDINARIAS                ...     FINALÍSTICO
4  SERVICOS DE LIMPEZA - MULHERES                ...  ADMINISTRATIVO
5  PRODUCAO DE AUDIOVISUAIS - ORDINARIAS         ...     FINALÍSTICO
6  SEGUROS - ORDINARIAS                          ...  ADMINISTRATIVO
7  DESPESAS COM CRIACAO E INCLUSAO DE PAGINAS NA ...     FINALÍSTICO
8  TRANSPORTES E VIAGENS - TRANSPORTE RODOVIARIO ...      INDEFINIDO
9  EVENTOS PROMOCIONAIS - DESPESAS ELEITORAIS    ...     FINALÍSTICO

Resumo categórico

       column dtype  null_count  null_percent  unique_values
0  nm_despesa   str           0           0.0            160
1    tp_gasto   str           0           0.0              3

Top valores categóricos

,column,value,count,percent
0,nm_despesa,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,1,0.62
1,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
2,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
3,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
4,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
5,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
6,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
7,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,1,0.62
8,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
9,nm_despesa,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,1,0.62
10,tp_gasto,FINALÍSTICO,85,53.12
11,tp_gasto,ADMINISTRATIVO,58,36.25
12,tp_gasto,INDEFINIDO,17,10.62

Arquivo salvo: ../data/05-output/notebooks/03-silver_classificacao_despesa.txt

Arquivo: receita.parquet

Shape:
(194844, 38)

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio,ind_dt_receita_nula
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1037150,1037150,2025-03-31,CONTRIBUICOES - DE FILIADOS,50.00,2025,False
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1035273,1035273,2025-03-11,CONTRIBUICOES - DE FILIADOS,50.00,2025,False
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1029365,1029365,2025-03-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,175274,NaN,2025-07-17,CONTRIBUICOES - OUTRAS CONTRIBUICOES,15.00,2025,False
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,73282907000164,PSTU,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,19318,19318,2025-04-23,DOACOES PARA MANUTENCAO DO PARTIDO - PESSOAS F...,10.00,2025,False
5,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1038474,NaN,2025-10-14,CONTRIBUICOES - OUTRAS CONTRIBUICOES,292.45,2025,False
6,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1043865,NaN,2025-11-12,CONTRIBUICOES - DE FILIADOS,70.00,2025,False
7,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1045979,NaN,2025-12-02,CONTRIBUICOES - OUTRAS CONTRIBUICOES,61.96,2025,False
8,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1026647,NaN,2025-08-25,CONTRIBUICOES - OUTRAS CONTRIBUICOES,1327.78,2025,False
9,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,984047,NaN,2025-03-27,CONTRIBUICOES - DE FILIADOS,200.00,2025,False

Estatísticas Numéricas

,count,mean,std,min,25%,50%,75%,max,null_count,null_percent
nr_zona,927.0,1.258900e+00,1.416451e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00,193917,99.524235
nr_zona_doador,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194844,100.000000
sq_candidato_doador,382.0,1.716251e+11,6.607862e+10,2.000205e+10,1.300020e+11,1.900019e+11,2.400020e+11,2.600024e+11,194462,99.803946
nr_candidato_doador,382.0,2.600759e+04,1.639037e+04,1.000000e+01,1.283675e+04,3.000100e+04,3.075775e+04,7.780000e+04,194462,99.803946
vl_receita,194844.0,7.960730e+03,2.217228e+05,0.000000e+00,3.975000e+01,8.000000e+01,2.500000e+02,3.726423e+07,0,0.000000
aa_exercicio,194844.0,2.025000e+03,0.000000e+00,2.025000e+03,2.025000e+03,2.025000e+03,2.025000e+03,2.025000e+03,0,0.000000

Resumo categórico

,column,dtype,null_count,null_percent,unique_values
0,hh_geracao,str,0,0.00,2
1,cd_tp_esfera_partidaria,str,0,0.00,5
2,ds_tp_espera_partidaria,str,0,0.00,5
3,sg_uf,str,0,0.00,28
4,cd_municipio,str,148413,76.17,2103
5,nm_municipio,str,148413,76.17,2064
6,cd_cnpj_prestador_conta,str,0,0.00,4134
7,sg_partido,str,0,0.00,34
8,nm_partido,str,0,0.00,34
9,cd_tp_origem_doacao,str,6419,3.29,7
10,ds_tp_origem_doacao,str,6419,3.29,7
11,cd_cpf_cnpj_doador,str,23384,12.00,49264
12,nm_doador,str,23384,12.00,49216
13,cd_tp_esfera_partidaria_doador,str,6419,3.29,6
14,ds_tp_esfera_partidaria_doador,str,6419,3.29,6
15,sg_uf_doador,str,6419,3.29,29
16,cd_municipio_doador,str,152784,78.41,545
17,nm_municipio_doador,str,152784,78.41,543
18,cd_candidato_cargo_doador,str,194462,99.80,6
19,ds_candidato_cargo_doador,str,194462,99.80,6
20,cd_tp_fonte_recurso,str,2793,1.43,5
21,ds_tp_fonte_recurso,str,2793,1.43,5
22,cd_tp_natureza_recurso,str,2793,1.43,3
23,ds_tp_natureza_recurso,str,2793,1.43,3
24,cd_tp_especie_recurso,str,3369,1.73,8
25,ds_tp_especie_recurso,str,3369,1.73,8
26,nr_recibo_doacao,str,22948,11.78,98882
27,nr_documento,str,167300,85.86,26337
28,ds_receita,str,2793,1.43,43

Top valores categóricos

,column,value,count,percent
0,hh_geracao,16:24:44,192051,98.57
1,hh_geracao,16:27:11,2793,1.43
2,cd_tp_esfera_partidaria,0,115530,59.29
3,cd_tp_esfera_partidaria,4,46431,23.83
4,cd_tp_esfera_partidaria,2,30857,15.84
...,...,...,...,...
217,ds_receita,JUROS E OUTRAS RENDAS - RENDIMENTOS DE APLICAC...,3050,1.57
218,ds_receita,nan,2793,1.43
219,ds_receita,OUTRAS RECEITAS DIVERSAS - RECEITAS COM EVENTO...,1580,0.81
220,ds_receita,GANHOS COM ATIVOS - VENDA DE MATERIAIS DE DIVU...,1275,0.65
221,ds_receita,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,889,0.46

Arquivo salvo: ../data/05-output/notebooks/03-silver_receita.txt

Arquivo: receita_enriquecida.parquet

Shape:
(264996, 48)

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,39.75,0.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,42.35,0.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,39.75,0.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,39.75,0.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,None,None,False,PRIVADA,False,True,False,0.0,30.00,0.0
5,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,None,None,False,PRIVADA,False,True,False,0.0,25.00,0.0
6,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,88.51,0.0
7,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,105.00,0.0
8,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,42.00,0.0
9,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,1116.43,0.0

Estatísticas Numéricas

,count,mean,std,min,25%,50%,75%,max,null_count,null_percent
nr_zona,2049.0,1.292826e+00,1.502651e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00,262947,99.226781
nr_zona_doador,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264996,100.000000
sq_candidato_doador,382.0,1.716251e+11,6.607862e+10,2.000205e+10,1.300020e+11,1.900019e+11,2.400020e+11,2.600024e+11,264614,99.855847
nr_candidato_doador,382.0,2.600759e+04,1.639037e+04,1.000000e+01,1.283675e+04,3.000100e+04,3.075775e+04,7.780000e+04,264614,99.855847
vl_receita,264996.0,1.061852e+04,1.987816e+05,0.000000e+00,3.000000e+01,9.069000e+01,3.870000e+02,3.726423e+07,0,0.000000
aa_exercicio,264996.0,2.025000e+03,0.000000e+00,2.025000e+03,2.025000e+03,2.025000e+03,2.025000e+03,2.025000e+03,0,0.000000
vl_receita_publica,264996.0,4.615210e+03,1.804503e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.614352e+07,0,0.000000
vl_receita_privada,264996.0,4.227605e+02,7.286438e+04,0.000000e+00,0.000000e+00,3.600000e+01,1.099000e+02,3.726423e+07,0,0.000000
vl_receita_partidaria,264996.0,4.684394e+03,3.243679e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.380000e+06,0,0.000000

Resumo categórico

,column,dtype,null_count,null_percent,unique_values
0,hh_geracao,str,0,0.00,2
1,cd_tp_esfera_partidaria,str,0,0.00,5
2,ds_tp_espera_partidaria,str,0,0.00,5
3,sg_uf,str,0,0.00,28
4,cd_municipio,str,190410,71.85,2103
5,nm_municipio,str,190410,71.85,2064
6,cd_cnpj_prestador_conta,str,0,0.00,4134
7,sg_partido,str,0,0.00,34
8,nm_partido,str,0,0.00,34
9,cd_tp_origem_doacao,str,25676,9.69,7
10,ds_tp_origem_doacao,str,25676,9.69,7
11,cd_cpf_cnpj_doador,str,93536,35.30,49264
12,nm_doador,str,93536,35.30,49216
13,cd_tp_esfera_partidaria_doador,str,25676,9.69,6
14,ds_tp_esfera_partidaria_doador,str,25676,9.69,6
15,sg_uf_doador,str,25676,9.69,29
16,cd_municipio_doador,str,207894,78.45,545
17,nm_municipio_doador,str,207894,78.45,543
18,cd_candidato_cargo_doador,str,264614,99.86,6
19,ds_candidato_cargo_doador,str,264614,99.86,6
20,cd_tp_fonte_recurso,str,11172,4.22,5
21,ds_tp_fonte_recurso,str,11172,4.22,5
22,cd_tp_natureza_recurso,str,11172,4.22,3
23,ds_tp_natureza_recurso,str,11172,4.22,3
24,cd_tp_especie_recurso,str,13476,5.09,8
25,ds_tp_especie_recurso,str,13476,5.09,8
26,nr_recibo_doacao,str,44572,16.82,98882
27,nr_documento,str,235931,89.03,26337
28,ds_receita,str,11172,4.22,43
29,nm_razao_social,str,263957,99.61,550
30,nm_fantasia,str,264503,99.81,113
31,tp_receita,str,0,0.00,4

Top valores categóricos

                      column                      value   count  percent
0                 hh_geracao                   16:24:44  253824    95.78
1                 hh_geracao                   16:27:11   11172     4.22
2    cd_tp_esfera_partidaria                          0  118914    44.87
3    cd_tp_esfera_partidaria                          4   74586    28.15
4    cd_tp_esfera_partidaria                          2   66749    25.19
..                       ...                        ...     ...      ...
241              nm_fantasia  AGROPECUARIA RURAL CENTER       8     0.00
242               tp_receita                    PRIVADA  170745    64.43
243               tp_receita                 PARTIDARIA   65860    24.85
244               tp_receita                     OUTROS   27914    10.53
245               tp_receita                    PUBLICA     477     0.18

[246 rows x 4 columns]

Arquivo salvo: ../data/05-output/notebooks/03-silver_receita_enriquecida.txt

Arquivo: cnpj.parquet

Shape:
(14879, 28)

Amostra:

,cd_cnpj,nm_razao_social,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,4748278000100,PROMERCADO MATERIAIS ELETRICOS E ILUMINACOES LTDA,PROMERCADO,2001-09-05 00:00:00,PR,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,COMERCIO VAREJISTA DE MATERIAL DE CONSTRUCAO,47.4,47.42-3,COMERCIO VAREJISTA DE MATERIAL ELETRICO,47.42-3/00,COMERCIO VAREJISTA DE MATERIAL ELETRICO,2026-04-13 05:46:14.493801000
1,16870671000143,ACL COMERCIO & SERVICO LTDA,NaN,2012-09-14 00:00:00,RN,NORDESTE,MATRIZ,2012-09-14 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,82,"SERVICOS DE ESCRITORIO, DE APOIO ADMINISTRATIV...",SERVICOS DE ESCRITORIO E APOIO ADMINISTRATIVO,82.1,82.11-3,SERVICOS COMBINADOS DE ESCRITORIO E APOIO ADMI...,82.11-3/00,SERVICOS COMBINADOS DE ESCRITORIO E APOIO ADMI...,2026-04-13 05:46:14.493801000
2,7701775000133,CARISMA INVESTIMENTOS E PARTICIPACOES S/A,CARISMA,2005-10-03 00:00:00,MT,CENTRO-OESTE,MATRIZ,2005-10-03 00:00:00,ATIVA,None,...,"ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVICOS ...",64,ATIVIDADES DE SERVICOS FINANCEIROS,ATIVIDADES DE SOCIEDADES DE PARTICIPACAO,64.6,64.62-0,HOLDINGS DE INSTITUICOES NAO FINANCEIRAS,64.62-0/00,HOLDINGS DE INSTITUICOES NAO-FINANCEIRAS,2026-04-13 05:46:14.493801000
3,10790572000175,BLA PRODUCOES LTDA,BLA.,2009-04-27 00:00:00,PE,NORDESTE,MATRIZ,2009-04-27 00:00:00,ATIVA,None,...,INFORMACAO E COMUNICACAO,59,"ATIVIDADES CINEMATOGRAFICAS, PRODUCAO DE VIDEO...","ATIVIDADES CINEMATOGRAFICAS, PRODUCAO DE VIDEO...",59.1,59.11-1,"ATIVIDADES DE PRODUCAO CINEMATOGRAFICA, DE VID...",59.11-1/02,PRODUCAO DE FILMES PARA PUBLICIDADE,2026-04-13 05:46:14.493801000
4,38353844000199,PETROBYTE ACESSORIOS DE INFORMATICA LTDA,PETROBYTE INFORMATICA,2020-09-04 00:00:00,RJ,SUDESTE,MATRIZ,2020-09-04 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,COMERCIO VAREJISTA DE EQUIPAMENTOS DE INFORMAT...,47.5,47.51-2,COMERCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,47.51-2/01,COMERCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,2026-04-13 05:46:14.493801000
5,51274355000100,BAR E RESTAURANTE BUFALO NA BRASA LTDA,NaN,1982-09-14 00:00:00,SP,SUDESTE,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ALOJAMENTO E ALIMENTACAO,56,ALIMENTACAO,RESTAURANTES E OUTROS SERVICOS DE ALIMENTACAO ...,56.1,56.11-2,RESTAURANTES E OUTROS ESTABELECIMENTOS DE SERV...,56.11-2/01,RESTAURANTES E SIMILARES,2026-04-13 05:46:14.493801000
6,6285022000121,JENILDO LIMA ANDRADE,HIDRO LIMA LIMPEZA E MANUTENCAO,2004-05-11 00:00:00,MS,CENTRO-OESTE,MATRIZ,NaN,ATIVA,None,...,OUTRAS ATIVIDADES DE SERVICOS,95,REPARACAO E MANUTENCAO DE EQUIPAMENTOS DE INFO...,REPARACAO E MANUTENCAO DE OBJETOS E EQUIPAMENT...,95.2,95.29-1,REPARACAO E MANUTENCAO DE OBJETOS E EQUIPAMENT...,95.29-1/99,REPARACAO E MANUTENCAO DE OUTROS OBJETOS E EQU...,2026-04-13 05:46:14.493801000
7,11050779000176,F. B. S. DOS SANTOS,DISTRIBUIDORA SOBRINHO,2009-08-14 00:00:00,RO,NORTE,MATRIZ,2009-08-14 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,"COMERCIO VAREJISTA DE PRODUTOS ALIMENTICIOS, B...",47.2,47.23-7,COMERCIO VAREJISTA DE BEBIDAS,47.23-7/00,COMERCIO VAREJISTA DE BEBIDAS,2026-04-13 05:46:14.493801000
8,10760199000100,DIRETORIO MUNICIPAL DO PARTIDO DOS TRABALHADOR...,PT - MONSENHOR TABOSA,2008-07-16 00:00:00,CE,NORDESTE,MATRIZ,2019-12-27 00:00:00,ATIVA,None,...,OUTRAS ATIVIDADES DE SERVICOS,94,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS NAO ES...,94.9,94.92-8,ATIVIDADES DE ORGANIZACOES POLITICAS,94.92-8/00,ATIVIDADES DE ORGANIZACOES POLITICAS,2026-04-13 05:46:14.493801000
9,22703695000100,CONDOMINIO DO EDIFICIO JK BUSINESS CENTER,CONDOMINIO DO EDIFICIO JK BUSINESS CENTER,2015-06-03 00:00:00,TO,NORTE,MATRIZ,2015-06-03 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,81,SERVICOS PARA EDIFICIOS E ATIVIDADES PAISAGIST...,SERVICOS COMBINADOS PARA APOIO A EDIFICIOS,81.1,81.12-5,CONDOMINIOS PREDIAIS,81.12-5/00,CONDOMINIOS PREDIAIS,2026-04-13 05:46:14.493801000

Resumo categórico

                     column dtype  null_count  null_percent  unique_values
0                   cd_cnpj   str           4          0.03          14876
1           nm_razao_social   str           4          0.03          13675
2               nm_fantasia   str        5607         37.68           8508
3               dt_abertura   str           4          0.03           7684
4                     ed_uf   str           4          0.03             28
5        nm_regiao_politica   str           4          0.03              6
6   nm_tipo_estabelecimento   str           4          0.03              3
7     dt_situacao_cadastral   str         229          1.54           4855
8     nm_situacao_cadastral   str           4          0.03              6
9           dt_sit_especial   str       14855         99.84             21
10     nm_situacao_especial   str       14855         99.84              4
11     cd_natureza_juridica   str           4          0.03             44
12     nm_natureza_juridica   str           4          0.03             44
13                 nm_porte   str           4          0.03              4
14        vl_capital_social   str           4          0.03           1344
15                  cd_cnae   str           4          0.03            550
16             in_principal   str           4          0.03              2
17          cd_nivel1_secao   str           4          0.03             21
18          nm_nivel1_secao   str           4          0.03             21
19        cd_nivel2_divisao   str           4          0.03             75
20        nm_nivel2_divisao   str           4          0.03             75
21          nm_nivel3_grupo   str           4          0.03            186
22          cd_nivel3_grupo   str           4          0.03            186
23         cd_nivel4_classe   str           4          0.03            351
24         nm_nivel4_classe   str           4          0.03            351
25      cd_nivel5_subclasse   str           4          0.03            550
26      nm_nivel5_subclasse   str           4          0.03            550
27    dt_atualizacao_pj_rfb   str           4          0.03              2

Top valores categóricos

,column,value,count,percent
0,cd_cnpj,nan,4,0.03
1,cd_cnpj,87537000130,1,0.01
2,cd_cnpj,124153000140,1,0.01
3,cd_cnpj,165731000197,1,0.01
4,cd_cnpj,370353000183,1,0.01
...,...,...,...,...
232,nm_nivel5_subclasse,PREPARACAO DE DOCUMENTOS E SERVICOS ESPECIALIZ...,253,1.70
233,nm_nivel5_subclasse,"BANCOS MULTIPLOS, COM CARTEIRA COMERCIAL",250,1.68
234,nm_nivel5_subclasse,"SERVICOS DE ORGANIZACAO DE FEIRAS, CONGRESSOS,...",236,1.59
235,dt_atualizacao_pj_rfb,2026-04-13 05:46:14.493801000,14875,99.97
236,dt_atualizacao_pj_rfb,nan,4,0.03

Arquivo salvo: ../data/05-output/notebooks/03-silver_cnpj.txt

Arquivo: despesa_enriquecida.parquet

Shape:
(206077, 41)

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nm_fantasia,is_cnpj_enriquecido,tp_gasto,tp_classificacao_origem,in_despesa_administrativa,in_despesa_finalistica,in_despesa_indefinida,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida
0,2026-04-25,16:26:12,2025,NaN,4,MUNICIPAL,PI,404,TANQUE DO PIAUI,-1,...,NaN,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.00,0.0,0.0
1,2026-04-25,16:26:12,2025,NaN,4,MUNICIPAL,BA,3371,BIRITINGA,-1,...,NaN,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.00,0.0,0.0
2,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PT-DIRETORIO MUNICIPAL DE TORRES,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,150.91,0.0,0.0
3,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,1423.95,0.0,0.0
4,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PT DIRETORIO MUNICIPAL EM SANTOS,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,11.64,0.0,0.0
5,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,108.27,0.0,0.0
6,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,39.38,0.0,0.0
7,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,13489.30,0.0,0.0
8,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,DIRETORIO REGIONAL DA PARAIBA,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,2004.45,0.0,0.0
9,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,540.55,0.0,0.0

Estatísticas Numéricas

,count,mean,std,min,25%,50%,75%,max,null_count,null_percent
aa_exercicio,206077.0,2.025000e+03,0.000000e+00,2025.0,2025.00,2025.00,2025.00,2025.00,0,0.0
nr_zona,206077.0,-9.869952e-01,3.603887e-01,-1.0,-1.00,-1.00,-1.00,9.00,0,0.0
aa_aidf,206077.0,8.711312e+01,4.132128e+02,-1.0,-1.00,-1.00,-1.00,2026.00,0,0.0
vl_gasto,206077.0,5.895136e+03,4.916293e+04,0.0,24.07,328.46,2513.70,3821394.33,0,0.0
vl_pagamento,206077.0,5.762548e+03,4.822538e+04,0.0,28.01,332.31,2511.43,3821394.33,0,0.0
vl_documento,206077.0,7.140402e+03,5.437051e+04,0.0,34.56,406.54,3000.00,3821394.33,0,0.0
sq_despesa,206077.0,3.140552e+06,1.580026e+06,-1.0,3646771.00,3927951.00,3996280.00,4069608.00,0,0.0
vl_despesa_administrativa,206077.0,3.108530e+03,2.200655e+04,0.0,0.00,39.38,717.95,3380000.00,0,0.0
vl_despesa_finalistica,206077.0,0.000000e+00,0.000000e+00,0.0,0.00,0.00,0.00,0.00,0,0.0
vl_despesa_indefinida,206077.0,1.100236e+03,1.215646e+04,0.0,0.00,0.00,0.00,1877000.00,0,0.0

Resumo categórico

                     column dtype  null_count  null_percent  unique_values
0                hh_geracao   str           0          0.00              2
1                tp_despesa   str       11172          5.42              5
2   cd_tp_esfera_partidaria   str           0          0.00              5
3   ds_tp_esfera_partidaria   str           0          0.00              5
4                     sg_uf   str           0          0.00             28
5              cd_municipio   str           0          0.00           2053
6              nm_municipio   str      167194         81.13           2014
7   cd_cnpj_prestador_conta   str           0          0.00           3930
8                sg_partido   str           0          0.00             34
9                nm_partido   str           0          0.00             34
10          cd_tp_documento   str       41475         20.13              7
11          ds_tp_documento   str       41475         20.13              7
12             nr_documento   str       57098         27.71          70772
13                  nr_aidf   str           0          0.00            250
14         cd_tp_fornecedor   str       13392          6.50              3
15         ds_tp_fornecedor   str       13392          6.50              3
16   cd_cpf_cnpj_fornecedor   str       13392          6.50          17719
17            nm_fornecedor   str       13392          6.50          18759
18                 ds_gasto   str           0          0.00            252
19         cd_fonte_despesa   str           0          0.00              5
20         ds_fonte_despesa   str       11172          5.42              5
21          nm_razao_social   str      129518         62.85           9813
22              nm_fantasia   str      154348         74.90           5847
23                 tp_gasto   str           0          0.00              3
24  tp_classificacao_origem   str           0          0.00              2

Top valores categóricos

                      column             value   count  percent
0                 hh_geracao          16:23:25  194905    94.58
1                 hh_geracao          16:26:12   11172     5.42
2                 tp_despesa                 G  163381    79.28
3                 tp_despesa                 D   28083    13.63
4                 tp_despesa               nan   11172     5.42
..                       ...               ...     ...      ...
177                 tp_gasto    ADMINISTRATIVO  146913    71.29
178                 tp_gasto        INDEFINIDO   49290    23.92
179                 tp_gasto       FINALÍSTICO    9874     4.79
180  tp_classificacao_origem      LOOKUP_EXATO  184273    89.42
181  tp_classificacao_origem  NAO_CLASSIFICADO   21804    10.58

[182 rows x 4 columns]

Arquivo salvo: ../data/05-output/notebooks/03-silver_despesa_enriquecida.txt

 ==================================================
	 Verificando arquivos 04-GOLD
 ==================================================

Arquivo: partido_ano_despesa.parquet

Shape:
(34, 11)

Amostra:

,sg_partido,aa_exercicio,vl_despesa_total,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida,qtd_fornecedores_unicos,pct_despesa_administrativa,pct_despesa_finalistica,pct_despesa_indefinida,ticket_medio_despesa
0,DC,2025,1954621.90,1344255.70,0.0,609566.20,94,68.773183,0.0,31.185888,20793.850000
1,DEM,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN
2,PATRIOTA,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN
3,PCB,2025,65168.97,54244.42,0.0,7401.34,28,83.236577,0.0,11.357154,2327.463214
4,PDT,2025,59102727.21,29707224.05,0.0,16019250.72,933,50.263711,0.0,27.104080,63346.974502
5,PODE,2025,67243623.91,32513369.42,0.0,17938500.63,874,48.351602,0.0,26.676880,76937.784794
6,PSB,2025,59464284.72,31736503.82,0.0,8183116.89,850,53.370698,0.0,13.761398,69957.982024
7,PSL,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN
8,SDD,2025,31227522.71,19385642.41,0.0,10795484.80,482,62.078707,0.0,34.570417,64787.391515
9,UP,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN

Estatísticas Numéricas

,count,mean,std,min,25%,50%,75%,max,null_count,null_percent
aa_exercicio,34.0,2.025000e+03,0.000000e+00,2025.000000,2025.000000,2.025000e+03,2.025000e+03,2.025000e+03,0,0.000000
vl_despesa_total,34.0,3.573094e+07,5.359648e+07,0.000000,16292.242500,1.387879e+07,4.991418e+07,2.261059e+08,0,0.000000
vl_despesa_administrativa,34.0,1.884108e+07,2.707414e+07,0.000000,13561.105000,7.231857e+06,3.122918e+07,1.086025e+08,0,0.000000
vl_despesa_finalistica,34.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000
vl_despesa_indefinida,34.0,6.668626e+06,1.039895e+07,0.000000,168.350000,4.654516e+06,7.837185e+06,5.207727e+07,0,0.000000
qtd_fornecedores_unicos,34.0,6.047059e+02,8.191487e+02,0.000000,3.000000,2.825000e+02,8.680000e+02,3.892000e+03,0,0.000000
pct_despesa_administrativa,25.0,5.871597e+01,1.403692e+01,40.133954,48.351602,5.458698e+01,6.811658e+01,9.965834e+01,9,26.470588
pct_despesa_finalistica,25.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,9,26.470588
pct_despesa_indefinida,25.0,2.088217e+01,1.123402e+01,0.341658,13.487976,2.039100e+01,2.710408e+01,5.367184e+01,9,26.470588
ticket_medio_despesa,25.0,5.213972e+04,3.859617e+04,2327.463214,23615.441081,4.893875e+04,6.870801e+04,1.914010e+05,9,26.470588

Resumo categórico

       column dtype  null_count  null_percent  unique_values
0  sg_partido   str           0           0.0             34

Top valores categóricos

       column      value  count  percent
0  sg_partido       AGIR      1     2.94
1  sg_partido     AVANTE      1     2.94
2  sg_partido  CIDADANIA      1     2.94
3  sg_partido         DC      1     2.94
4  sg_partido        DEM      1     2.94
5  sg_partido  DEMOCRATA      1     2.94
6  sg_partido        MDB      1     2.94
7  sg_partido   MOBILIZA      1     2.94
8  sg_partido       NOVO      1     2.94
9  sg_partido   PATRIOTA      1     2.94

Arquivo salvo: ../data/05-output/notebooks/04-gold_partido_ano_despesa.txt

Arquivo: partido_ano_receita.parquet

Shape:
(34, 10)

Amostra:

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,CIDADANIA,2025,1.175145e+07,3.815505e+06,501646.01,7.429742e+06,79,32.468366,4.268799,148752.586076
1,DEM,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
2,PATRIOTA,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
3,PC DO B,2025,3.331525e+07,1.982971e+07,3480874.39,9.982024e+06,2145,59.521410,10.448290,15531.586876
4,PL,2025,4.354022e+08,2.086250e+08,40965912.74,1.419754e+08,741,47.915465,9.408751,587587.374494
5,PODE,2025,1.072410e+08,5.878967e+07,2129297.21,4.629979e+07,529,54.820145,1.985525,202724.000870
6,PRTB,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
7,PT,2025,3.664338e+08,1.529199e+08,33868524.01,1.792951e+08,26006,41.731939,9.242741,14090.355175
8,REPUBLICANOS,2025,2.073313e+08,9.639831e+07,4479893.25,6.013558e+07,1874,46.494811,2.160741,110635.713682
9,UP,2025,6.243870e+03,0.000000e+00,6243.87,0.000000e+00,37,0.000000,100.000000,168.753243

Estatísticas Numéricas

,count,mean,std,min,25%,50%,75%,max,null_count,null_percent
aa_exercicio,34.0,2.025000e+03,0.000000e+00,2025.000000,2025.000000,2.025000e+03,2.025000e+03,2.025000e+03,0,0.000000
vl_receita_total,34.0,8.276073e+07,1.127982e+08,0.000000,72116.397500,2.593746e+07,1.171463e+08,4.354022e+08,0,0.000000
vl_receita_publica,34.0,3.597095e+07,5.713086e+07,0.000000,0.000000,8.342772e+06,5.138232e+07,2.090511e+08,0,0.000000
vl_receita_privada,34.0,3.294996e+06,8.812276e+06,0.000000,39763.617500,6.222411e+05,2.195369e+06,4.096591e+07,0,0.000000
vl_receita_partidaria,34.0,3.651016e+07,5.265732e+07,0.000000,10680.000000,8.705883e+06,4.668626e+07,1.792951e+08,0,0.000000
qtd_doadores_unicos,34.0,1.453559e+03,4.683072e+03,0.000000,38.000000,1.385000e+02,7.287500e+02,2.600600e+04,0,0.000000
pct_receita_publica,27.0,3.357933e+01,2.779628e+01,0.000000,0.000000,3.692340e+01,5.136781e+01,8.598392e+01,7,20.588235
pct_receita_privada,27.0,1.840766e+01,3.081083e+01,0.282003,1.260690,2.529795e+00,1.116413e+01,1.000000e+02,7,20.588235
ticket_medio_receita,27.0,2.824521e+05,4.592772e+05,168.753243,16845.060188,1.106357e+05,2.808362e+05,1.914395e+06,7,20.588235

Resumo categórico

       column dtype  null_count  null_percent  unique_values
0  sg_partido   str           0           0.0             34

Top valores categóricos

       column      value  count  percent
0  sg_partido       AGIR      1     2.94
1  sg_partido     AVANTE      1     2.94
2  sg_partido  CIDADANIA      1     2.94
3  sg_partido         DC      1     2.94
4  sg_partido        DEM      1     2.94
5  sg_partido  DEMOCRATA      1     2.94
6  sg_partido        MDB      1     2.94
7  sg_partido   MOBILIZA      1     2.94
8  sg_partido       NOVO      1     2.94
9  sg_partido   PATRIOTA      1     2.94

Arquivo salvo: ../data/05-output/notebooks/04-gold_partido_ano_receita.txt