# Verificação rápida dos dados

In [11]:
from IPython.display import display
import duckdb
import pandas as pd
import os

PARQUET_BRONZE_DIR = "../data/02-bronze"
PARQUET_SILVER_DIR = "../data/03-silver"
PARQUET_GOLD_DIR = "../data/04-gold"

OUTPUT_DIR = "../data/05-output/notebooks"

In [ ]:
# =========================================================
# Funções auxiliares
# =========================================================

def get_parquet_files(dir_path):
    """Retorna uma lista de arquivos Parquet em um diretório específico."""

    if not os.path.exists(dir_path):
        return []

    return [
        os.path.join(dir_path, x)
        for x in os.listdir(dir_path)
        if x.endswith(".parquet")
    ]

def verificar_dados(parquet_file_names):
    """
    Lê arquivos Parquet completos para métricas
    e gera uma amostra aleatória para visualização.
    """

    resultados = {}

    for file in parquet_file_names:

        print(f"\nArquivo: {file}")

        # =====================================================
        # DataFrame completo
        # =====================================================

        df_full = duckdb.sql(
            f"""
            SELECT *
            FROM read_parquet('{file}')
            """
        ).df()

        # =====================================================
        # Amostra aleatória
        # =====================================================

        df_sample = duckdb.sql(
            f"""
            SELECT *
            FROM read_parquet('{file}')
            USING SAMPLE 10 ROWS
            """
        ).df()

        print("\nShape:", df_full.shape)

        print("\nColunas:")
        print(df_full.dtypes)

        print("\nAmostra aleatória:")
        display(df_sample)

        resultados[file] = {
            "full": df_full,
            "sample": df_sample
        }

    return resultados

def analisar_estatisticas(df):
    """
    Gera análises estatísticas básicas separando
    colunas numéricas e categóricas.
    """

    # =====================================================
    # Colunas numéricas
    # =====================================================

    df_numerico = df.select_dtypes(include=["number"])

    if not df_numerico.empty:

        print("\n" + "=" * 80)
        print("ESTATÍSTICAS - COLUNAS NUMÉRICAS")
        print("=" * 80)

        stats_numericas = df_numerico.describe().T

        stats_numericas["null_count"] = df_numerico.isnull().sum()

        stats_numericas["null_percent"] = (
            df_numerico.isnull().sum() / len(df_numerico)
        ) * 100

        display(stats_numericas)

    else:
        print("\nNenhuma coluna numérica encontrada.")

    # =====================================================
    # Colunas categóricas
    # =====================================================

    df_categorico = df.select_dtypes(
        include=["object", "category", "string"]
    )

    if not df_categorico.empty:

        print("\n" + "=" * 80)
        print("ESTATÍSTICAS - COLUNAS CATEGÓRICAS")
        print("=" * 80)

        stats_categoricas = []

        for col in df_categorico.columns:

            stats_categoricas.append({
                "coluna": col,
                "nulos": df_categorico[col].isnull().sum(),
                "%_null": round(
                    (df_categorico[col].isnull().sum() / len(df)) * 100,
                    2
                ),
                "valores_unicos": df_categorico[col].nunique(),
                "valor_mais_frequente": (
                    df_categorico[col].mode().iloc[0]
                    if not df_categorico[col].mode().empty
                    else None
                ),
                "frequencia_topo": (
                    df_categorico[col].value_counts().iloc[0]
                    if not df_categorico[col].value_counts().empty
                    else None
                )
            })

        stats_categoricas = pd.DataFrame(stats_categoricas)

        display(stats_categoricas)

    else:
        print("\nNenhuma coluna categórica encontrada.")

def salvar_output_txt(resultados, output_dir, camada):

    os.makedirs(output_dir, exist_ok=True)

    map_camada = {
        "bronze": "02-BRONZE",
        "silver": "03-SILVER",
        "gold": "04-GOLD"
    }

    for file_path, data in resultados.items():

        df = data["full"]
        df_sample = data["sample"]

        parquet_name = os.path.basename(file_path)

        txt_name = parquet_name.replace(".parquet", ".txt")

        output_file = os.path.join(
            output_dir,
            f"{map_camada[camada]}_{txt_name}"
        )

        null_counts = df.isnull().sum()

        with open(output_file, "w", encoding="utf-8") as f:

            f.write("=" * 100 + "\n")
            f.write(f"ARQUIVO: {parquet_name}\n")
            f.write("=" * 100 + "\n\n")

            # =================================================
            # Shape
            # =================================================

            f.write("SHAPE\n")
            f.write("-" * 100 + "\n")
            f.write(f"{df.shape}\n\n")

            # =================================================
            # Colunas / Tipos / Nulos
            # =================================================

            f.write("COLUNAS / TIPOS / NULOS\n")
            f.write("-" * 100 + "\n")

            for col in df.columns:

                null_count = null_counts[col]
                null_percent = (null_count / len(df)) * 100

                f.write(
                    f"{col:<30} | "
                    f"Tipo: {str(df[col].dtype):<15} | "
                    f"Nulos: {null_count:<10} | "
                    f"% Null: {null_percent:>6.2f}%\n"
                )

            # =================================================
            # Sample
            # =================================================

            f.write("\nAMOSTRA ALEATÓRIA\n")
            f.write("-" * 100 + "\n")
            f.write(df_sample.to_string(index=False))
            f.write("\n")

        print(f"TXT salvo em: {output_file}")

## Visualiza todos os dados

In [23]:
# =========================================================
# Execução
# =========================================================

PARQUET_BRONZE_FILE_NAME = get_parquet_files(PARQUET_BRONZE_DIR)
PARQUET_SILVER_FILE_NAME = get_parquet_files(PARQUET_SILVER_DIR)
PARQUET_GOLD_FILE_NAME = get_parquet_files(PARQUET_GOLD_DIR)


print("="*50, "\n\t Verificando arquivos BRONZE \n", "="*50)
bronze_resultados = verificar_dados(PARQUET_BRONZE_FILE_NAME)
salvar_output_txt(bronze_resultados, OUTPUT_DIR, "bronze")


print("\n\n", "="*50, "\n\t Verificando arquivos SILVER \n", "="*50)
silver_resultados = verificar_dados(PARQUET_SILVER_FILE_NAME)
salvar_output_txt(silver_resultados, OUTPUT_DIR, "silver")


print("\n\n", "="*50, "\n\t Verificando arquivos GOLD \n", "="*50)
gold_resultados = verificar_dados(PARQUET_GOLD_FILE_NAME)
salvar_output_txt(gold_resultados, OUTPUT_DIR, "gold")

==================================================
	 Verificando arquivos BRONZE
 ==================================================

Arquivo: ../data/02-bronze/despesa.parquet

Shape: (196033, 30)

Colunas:
DT_GERACAO                 str
HH_GERACAO                 str
AA_EXERCICIO               str
TP_DESPESA                 str
CD_TP_ESFERA_PARTIDARIA    str
DS_TP_ESFERA_PARTIDARIA    str
SG_UF                      str
CD_MUNICIPIO               str
NM_MUNICIPIO               str
NR_ZONA                    str
NR_CNPJ_PRESTADOR_CONTA    str
SG_PARTIDO                 str
NM_PARTIDO                 str
CD_TP_DOCUMENTO            str
DS_TP_DOCUMENTO            str
NR_DOCUMENTO               str
AA_AIDF                    str
NR_AIDF                    str
CD_TP_FORNECEDOR           str
DS_TP_FORNECEDOR           str
NR_CPF_CNPJ_FORNECEDOR     str
NM_FORNECEDOR              str
DS_GASTO                   str
DT_PAGAMENTO               str
VR_GASTO                   str
VR_PAGAMENTO               str
VR_DOCUMENTO               str
CD_FONTE_DESPESA           str
DS_FONTE_DESPESA           str
SQ_DESPESA                 str
dtype: object

Amostra aleatória:

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,DS_GASTO,DT_PAGAMENTO,VR_GASTO,VR_PAGAMENTO,VR_DOCUMENTO,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:26:12,2025,#NULO#,4,Municipal,RS,8935,TRAMANDAÍ,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
1,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,51796316000172,Direção Municipal/Comissão Provisória - PT - F...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,08/09/2025,"50,06","50,06","50,06",2,Outros Recursos,-1
2,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,80892029000164,Direção Municipal/Comissão Provisória - PT - M...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,13/05/2025,"130,81","130,81","130,81",2,Outros Recursos,-1
3,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,43336767000107,Direção Municipal/Comissão Provisória - PT - S...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,13/05/2025,"884,01","884,01","884,01",2,Outros Recursos,-1
4,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,08963082000181,Direção Estadual/Distrital - PL - RONDÔNIA,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - FUNDO P...,04/04/2025,40000,40000,40000,1,Fundo Partidário,-1
5,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,25173657000181,Direção Municipal/Comissão Provisória - NOVO -...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,17/10/2025,6922,6922,6922,2,Outros Recursos,-1
6,25/04/2026,16:23:25,2025,G,1,Distrital,DF,-1,#NULO#,-1,...,15754475000140,HostGator Brasil Ltda,TELECOMUNICAÇÕES E INTERNET - ORDINÁRIAS,11/06/2025,"655,79","655,79","655,79",1,Fundo Partidário,3940310
7,25/04/2026,16:23:25,2025,G,1,Distrital,DF,-1,#NULO#,-1,...,82878889134,Joana DArc Gomes Cardoso,PESSOAL - SALÁRIOS E ORDENADOS - ORDINÁRIAS,03/02/2025,"3908,02","3908,02","3908,02",1,Fundo Partidário,3563840
8,25/04/2026,16:23:25,2025,G,2,Estadual,GO,-1,#NULO#,-1,...,00000000000191,BANCO DO BRASIL S.A.,DESPESAS FINANCEIRAS - COMISSÕES E TARIFAS BAN...,10/02/2025,"73,8","73,8","73,8",1,Fundo Partidário,3928918
9,25/04/2026,16:23:25,2025,G,2,Estadual,PE,-1,#NULO#,-1,...,50172126000111,50.172.126 RODRIGO PESSOA BARBOZA DE ANDRADE,SERVIÇOS TÉCNICO-PROFISSIONAIS - OUTROS SERVIÇ...,06/01/2025,3000,3000,3000,1,Fundo Partidário,3580005

Arquivo: ../data/02-bronze/classificacao_despesa.parquet

Shape: (160, 2)

Colunas:
DESPESA                                                                                                                                       str
CLASSIFICACAO                                                                                                                                 str
dtype: object

Amostra aleatória:

,DESPESA,CLASSIFICACAO
0,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,ADMINISTRATIVO
1,SERVICOS TECNICO-PROFISSIONAIS - SERVICOS CONT...,ADMINISTRATIVO
2,PESSOAL - SALARIOS E ORDENADOS - ORDINARIAS ...,ADMINISTRATIVO
3,TRIBUTOS - OUTROS TRIBUTOS - ORDINARIAS ...,ADMINISTRATIVO
4,PESSOAL - O SALARIO - ORDINARIAS ...,ADMINISTRATIVO
5,"TRANSPORTES E VIAGENS - COMBUSTIVEIS, OLEOS E ...",INDEFINIDO
6,PRODUCAO DE AUDIOVISUAIS - MULHERES ...,FINALÍSTICO
7,"TRANSPORTES E VIAGENS - COMBUSTIVEIS, OLEOS E ...",FINALÍSTICO
8,TRANSPORTES E VIAGENS - OUTRAS DESPESAS COM TR...,FINALÍSTICO
9,SERVICOS TECNICO-PROFISSIONAIS - SERVICOS DE C...,FINALÍSTICO

Arquivo: ../data/02-bronze/receita.parquet

Shape: (194844, 36)

Colunas:
DT_GERACAO                        str
HH_GERACAO                        str
CD_TP_ESFERA_PARTIDARIA           str
DS_TP_ESPERA_PARTIDARIA           str
SG_UF                             str
CD_MUNICIPIO                      str
NM_MUNICIPIO                      str
NR_ZONA                           str
NR_CNPJ_PRESTADOR_CONTA           str
SG_PARTIDO                        str
NM_PARTIDO                        str
CD_TP_ORIGEM_DOACAO               str
DS_TP_ORIGEM_DOACAO               str
NR_CPF_CNPJ_DOADOR                str
NM_DOADOR                         str
CD_TP_ESFERA_PARTIDARIA_DOADOR    str
DS_TP_ESFERA_PARTIDARIA_DOADOR    str
SG_UF_DOADOR                      str
CD_MUNICIPIO_DOADOR               str
NM_MUNICIPIO_DOADOR               str
NR_ZONA_DOADOR                    str
SQ_CANDIDATO_DOADOR               str
NR_CANDIDATO_DOADOR               str
CD_CANDIDATO_CARGO_DOADOR         str
DS_CANDIDATO_CARGO_DOADOR         str
CD_TP_FONTE_RECURSO               str
DS_TP_FONTE_RECURSO               str
CD_TP_NATUREZA_RECURSO            str
DS_TP_NATUREZA_RECURSO            str
CD_TP_ESPECIE_RECURSO             str
DS_TP_ESPECIE_RECURSO             str
NR_RECIBO_DOACAO                  str
NR_DOCUMENTO                      str
DT_RECEITA                        str
DS_RECEITA                        str
VR_RECEITA                        str
dtype: object

Amostra aleatória:

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,SG_PARTIDO,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,DT_RECEITA,DS_RECEITA,VR_RECEITA
0,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1029662,1029662,11/03/2025,CONTRIBUIÇÕES - DE FILIADOS,"39,75"
1,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1014970,1014970,03/01/2025,CONTRIBUIÇÕES - DE FILIADOS,50
2,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1028573,1028573,11/02/2025,CONTRIBUIÇÕES - DE FILIADOS,"39,75"
3,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1028742,1028742,15/01/2025,CONTRIBUIÇÕES - DE FILIADOS,"39,75"
4,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,54956495000156,PC do B,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,184778,#NULO#,14/11/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,20
5,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,54956495000156,PC do B,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,178519,#NULO#,08/09/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,45
6,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,73282907000164,PSTU,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,#NULO#,#NULO#,09/04/2025,DOAÇÕES PARA MANUTENÇÃO DO PARTIDO - FINANCIAM...,1486
7,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1035621,#NULO#,06/10/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,"1175,68"
8,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,991304,#NULO#,28/04/2025,CONTRIBUIÇÕES - DE FILIADOS,30
9,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1017707,#NULO#,03/07/2025,CONTRIBUIÇÕES - DE PARLAMENTARES,"2744,95"

Arquivo: ../data/02-bronze/cnpj.parquet

Shape: (14879, 28)

Colunas:
cd_cnpj                    str
nm_empresarial             str
nm_fantasia                str
dt_abertura                str
ed_uf                      str
nm_regiao_politica         str
nm_tipo_estabelecimento    str
dt_situacao_cadastral      str
nm_situacao_cadastral      str
dt_sit_especial            str
nm_situacao_especial       str
cd_natureza_juridica       str
nm_natureza_juridica       str
nm_porte                   str
vl_capital_social          str
cd_cnae                    str
in_principal               str
cd_nivel1_secao            str
nm_nivel1_secao            str
cd_nivel2_divisao          str
nm_nivel2_divisao          str
nm_nivel3_grupo            str
cd_nivel3_grupo            str
cd_nivel4_classe           str
nm_nivel4_classe           str
cd_nivel5_subclasse        str
nm_nivel5_subclasse        str
dt_atualizacao_pj_rfb      str
dtype: object

Amostra aleatória:

,cd_cnpj,nm_empresarial,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,1066616000128,STYLO GRAFICA E EDITORA LTDA,NaN,1996-02-28 00:00:00,GO,CENTRO-OESTE,Matriz,2004-12-24 00:00:00,Ativa,None,...,INFORMAÇÃO E COMUNICAÇÃO,58,EDIÇÃO E EDIÇÃO INTEGRADA À IMPRESSÃO,"Edição integrada à impressão de livros, jornai...",58.2,58.29-8,"Edição integrada à impressão de cadastros, lis...",58.29-8/00,"Edição integrada à impressão de cadastros, lis...",2026-04-13 05:46:14.493801000
1,15659805000119,DOIS AMORES COMERCIO DE DOCES E SALGADOS LTDA,DOIS AMORES,2012-06-04 00:00:00,MS,CENTRO-OESTE,Matriz,2012-06-04 00:00:00,Ativa,None,...,INDÚSTRIAS DE TRANSFORMAÇÃO,10,FABRICAÇÃO DE PRODUTOS ALIMENTÍCIOS,Fabricação de outros produtos alimentícios,10.9,10.91-1,Fabricação de produtos de panificação,10.91-1/02,Fabricação de produtos de padaria e confeitari...,2026-04-13 05:46:14.493801000
2,31300407000168,RM BRASIL FILMES LTDA,RM BRASIL FILMES,2018-08-22 00:00:00,MG,SUDESTE,Matriz,2018-08-22 00:00:00,Ativa,None,...,"ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS",74,"OUTRAS ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E...",Atividades fotográficas e similares,74.2,74.20-0,Atividades fotográficas e similares,74.20-0/04,Filmagem de festas e eventos,2026-04-13 05:46:14.493801000
3,31536616000105,FIGUEIREDU'S CONFECCOES LTDA,FIGUEIREDU'S CONFECCOES,2018-09-18 00:00:00,DF,CENTRO-OESTE,Matriz,2018-09-18 00:00:00,Ativa,None,...,INDÚSTRIAS DE TRANSFORMAÇÃO,14,CONFECÇÃO DE ARTIGOS DO VESTUÁRIO E ACESSÓRIOS,Confecção de artigos do vestuário e acessórios,14.1,14.12-6,"Confecção de peças do vestuário, exceto roupas...",14.12-6/01,"Confecção de peças de vestuário, exceto roupas...",2026-04-13 05:46:14.493801000
4,41800867000109,ADRIANO ROMAO DE ANDRADE LTDA,ARA PISOS E REVESTIMENTOS,2021-05-03 00:00:00,DF,CENTRO-OESTE,Matriz,2021-05-03 00:00:00,Ativa,None,...,CONSTRUÇÃO,43,SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO,Obras de acabamento,43.3,43.30-4,Obras de acabamento,43.30-4/05,Aplicação de revestimentos e de resinas em int...,2026-04-13 05:46:14.493801000
5,59702841000193,IMPACTO SOLUCOES LTDA,NaN,2025-02-27 00:00:00,PR,SUL,Matriz,2025-02-27 00:00:00,Ativa,None,...,EDUCAÇÃO,85,EDUCAÇÃO,Outras atividades de ensino,85.9,85.99-6,Atividades de ensino não especificadas anterio...,85.99-6/04,Treinamento em desenvolvimento profissional e ...,2026-04-13 05:46:14.493801000
6,26752857000151,DEPARTAMENTO ESTADUAL DE TRANSITO - DETRAN - TO,DETRAN,1992-08-10 00:00:00,TO,NORTE,Matriz,1998-07-28 00:00:00,Ativa,None,...,"ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL",84,"ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL",Serviços coletivos prestados pela administraçã...,84.2,84.24-8,Segurança e ordem pública,84.24-8/00,Segurança e ordem pública,2026-04-13 05:46:14.493801000
7,2348282000148,VALDIR ALVES DA COSTA,CACU HOTEL,1986-09-02 00:00:00,GO,CENTRO-OESTE,Matriz,2005-11-03 00:00:00,Ativa,None,...,ALOJAMENTO E ALIMENTAÇÃO,55,ALOJAMENTO,Hotéis e similares,55.1,55.10-8,Hotéis e similares,55.10-8/01,Hotéis,2026-04-13 05:46:14.493801000
8,23845461000160,COMISSAO PROVISORIA DO PARTIDO SOCIALISMO E LI...,COMISSAO PROVISORIA PSOL RIO CLARO - SP,2012-11-15 00:00:00,SP,SUDESTE,Matriz,2020-09-04 00:00:00,Ativa,None,...,OUTRAS ATIVIDADES DE SERVIÇOS,94,ATIVIDADES DE ORGANIZAÇÕES ASSOCIATIVAS,Atividades de organizações associativas não es...,94.9,94.92-8,Atividades de organizações políticas,94.92-8/00,Atividades de organizações políticas,2026-04-13 05:46:14.493801000
9,19892683000167,19.892.683 ELIZA MARIA DE CASTRO SOUSA MACHADO,NaN,2014-03-17 00:00:00,PB,NORDESTE,Matriz,2014-03-17 00:00:00,Ativa,None,...,OUTRAS ATIVIDADES DE SERVIÇOS,95,REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS DE INFO...,Reparação e manutenção de objetos e equipament...,95.2,95.29-1,Reparação e manutenção de objetos e equipament...,95.29-1/02,Chaveiros,2026-04-13 05:46:14.493801000

TXT salvo em: ../data/05-output/notebooks/02-BRONZE_despesa.txt
TXT salvo em: ../data/05-output/notebooks/02-BRONZE_classificacao_despesa.txt
TXT salvo em: ../data/05-output/notebooks/02-BRONZE_receita.txt
TXT salvo em: ../data/05-output/notebooks/02-BRONZE_cnpj.txt


 ==================================================
	 Verificando arquivos SILVER
 ==================================================

Arquivo: ../data/03-silver/despesa.parquet

Shape: (196033, 30)

Colunas:
dt_geracao                 datetime64[us]
hh_geracao                            str
aa_exercicio                        int64
tp_despesa                            str
cd_tp_esfera_partidaria               str
ds_tp_esfera_partidaria               str
sg_uf                                 str
cd_municipio                          str
nm_municipio                          str
nr_zona                             int64
cd_cnpj_prestador_conta               str
sg_partido                            str
nm_partido                            str
cd_tp_documento                       str
ds_tp_documento                       str
nr_documento                          str
aa_aidf                             int64
nr_aidf                               str
cd_tp_fornecedor                      str
ds_tp_fornecedor                      str
cd_cpf_cnpj_fornecedor                str
nm_fornecedor                         str
ds_gasto                              str
dt_pagamento               datetime64[us]
vl_gasto                          float64
vl_pagamento                      float64
vl_documento                      float64
cd_fonte_despesa                      str
ds_fonte_despesa                      str
sq_despesa                          int64
dtype: object

Amostra aleatória:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:23:25,2025,A,4,MUNICIPAL,SP,6163,ARARAQUARA,-1,...,NaN,NaN,DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...,2025-06-30,0.00,0.05,0.05,2,OUTROS RECURSOS,-1
1,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,03195803000137,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - P...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-04-24,130.81,130.81,130.81,2,OUTROS RECURSOS,-1
2,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,35050822000161,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - A...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-05-23,183.43,183.43,183.43,2,OUTROS RECURSOS,-1
3,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,24130411000160,DIRECAO ESTADUAL/DISTRITAL - PSDB - PERNAMBUCO,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,2025-11-27,4738.00,4738.00,4738.00,1,FUNDO PARTIDARIO,-1
4,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,03645895000100,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PCDOB ...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-01-14,305.91,305.91,305.91,2,OUTROS RECURSOS,-1
5,2026-04-25,16:23:25,2025,G,1,DISTRITAL,DF,-1,NaN,-1,...,57961778187,JEFFERSON LOURENCO DE OLIVEIRA,PESSOAL - SALARIOS E ORDENADOS - ORDINARIAS,2025-10-31,3416.20,3416.20,4558.99,1,FUNDO PARTIDARIO,4056746
6,2026-04-25,16:23:25,2025,G,1,DISTRITAL,DF,-1,NaN,-1,...,00000000478997,"AGENCIA DO BANCO DO BRASIL, LAGO SUL, QI 11",DESPESAS FINANCEIRAS - COMISSOES E TARIFAS BAN...,2025-08-01,13.00,13.00,13.00,1,FUNDO PARTIDARIO,3933469
7,2026-04-25,16:23:25,2025,G,2,ESTADUAL,SE,-1,NaN,-1,...,02558157000162,TELEFONICA BRASIL S A,TELECOMUNICACOES E INTERNET - ORDINARIAS,2025-10-09,349.34,349.34,349.34,1,FUNDO PARTIDARIO,3979907
8,2026-04-25,16:23:25,2025,G,2,ESTADUAL,BA,-1,NaN,-1,...,05781888000241,INDUSTRIA E COMERCIO DONA FLOR LTDA,MATERIAL DE CONSUMO - MATERIAIS DE COPA E COZI...,2025-07-29,312.00,312.00,312.00,1,FUNDO PARTIDARIO,3948637
9,2026-04-25,16:23:25,2025,G,2,ESTADUAL,MA,-1,NaN,-1,...,42635041000102,G.R. SALES DE SALES,EVENTOS PROMOCIONAIS - MULHERES,2025-03-17,11900.00,11900.00,11900.00,1,FUNDO PARTIDARIO,3968556

Arquivo: ../data/03-silver/classificacao_despesa.parquet

Shape: (160, 2)

Colunas:
nm_despesa    str
tp_gasto      str
dtype: object

Amostra aleatória:

                                          nm_despesa        tp_gasto
0  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
1  RADIO E TELEVISAO - MULHERES                  ...     FINALÍSTICO
2  COPIAS, ENCADERNACOES E SERVICOS SIMILARES - O...  ADMINISTRATIVO
3  PRODUCAO DE AUDIOVISUAIS - ORDINARIAS         ...     FINALÍSTICO
4  TRANSPORTES E VIAGENS - FRETES E CARRETOS - OR...      INDEFINIDO
5  OUTRAS DESPESAS COM PROPAGANDA DOUTRINARIA E P...     FINALÍSTICO
6  ASSUNCAO DE DIVIDAS DE CAMPANHA - DIVIDAS DE D...     FINALÍSTICO
7  SEMINARIOS - MULHERES                         ...     FINALÍSTICO
8  SERVICOS TECNICO-PROFISSIONAIS - SERVICOS DE C...     FINALÍSTICO
9  EVENTOS PROMOCIONAIS - DESPESAS ELEITORAIS    ...     FINALÍSTICO

Arquivo: ../data/03-silver/receita.parquet

Shape: (194844, 38)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                                 str
nm_municipio                                 str
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                          str
nm_municipio_doador                          str
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                                 str
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
dtype: object

Amostra aleatória:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio,ind_dt_receita_nula
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1019656,1019656,2025-01-15,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1035885,1035885,2025-03-11,CONTRIBUICOES - DE FILIADOS,42.35,2025,False
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1025214,1025214,2025-02-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1032967,1032967,2025-03-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1019243,1019243,2025-01-15,DOACOES PARA MANUTENCAO DO PARTIDO - PESSOAS F...,20.00,2025,False
5,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1031777,1031777,2025-02-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
6,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1025374,1025374,2025-02-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
7,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1019060,NaN,2025-07-07,CONTRIBUICOES - OUTRAS CONTRIBUICOES,52.40,2025,False
8,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1040505,NaN,2025-10-29,CONTRIBUICOES - OUTRAS CONTRIBUICOES,24.00,2025,False
9,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1025446,NaN,2025-08-12,CONTRIBUICOES - DE FILIADOS,30.00,2025,False

Arquivo: ../data/03-silver/receita_enriquecida.parquet

Shape: (264996, 48)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                                 str
nm_municipio                                 str
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                          str
nm_municipio_doador                          str
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                                 str
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
nm_razao_social                              str
nm_fantasia                                  str
is_cnpj_enriquecido                         bool
tp_receita                                   str
in_receita_publica                          bool
in_receita_privada                          bool
in_receita_partidaria                       bool
vl_receita_publica                       float64
vl_receita_privada                       float64
vl_receita_partidaria                    float64
dtype: object

Amostra aleatória:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,50.00,0.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,39.75,0.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,42.35,0.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,50.00,0.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,None,None,False,PRIVADA,False,True,False,0.0,15.00,0.0
5,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,None,None,False,PRIVADA,False,True,False,0.0,50.00,0.0
6,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,30.00,0.0
7,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,3970.27,0.0
8,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,15.00,0.0
9,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,15.00,0.0

Arquivo: ../data/03-silver/cnpj.parquet

Shape: (14879, 28)

Colunas:
cd_cnpj                    str
nm_razao_social            str
nm_fantasia                str
dt_abertura                str
ed_uf                      str
nm_regiao_politica         str
nm_tipo_estabelecimento    str
dt_situacao_cadastral      str
nm_situacao_cadastral      str
dt_sit_especial            str
nm_situacao_especial       str
cd_natureza_juridica       str
nm_natureza_juridica       str
nm_porte                   str
vl_capital_social          str
cd_cnae                    str
in_principal               str
cd_nivel1_secao            str
nm_nivel1_secao            str
cd_nivel2_divisao          str
nm_nivel2_divisao          str
nm_nivel3_grupo            str
cd_nivel3_grupo            str
cd_nivel4_classe           str
nm_nivel4_classe           str
cd_nivel5_subclasse        str
nm_nivel5_subclasse        str
dt_atualizacao_pj_rfb      str
dtype: object

Amostra aleatória:

,cd_cnpj,nm_razao_social,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,2223966010500,ATLANTICA HOTELS INTERNATIONAL BRASIL LTDA,ATLANTICA HOTELS,2018-06-04 00:00:00,SP,SUDESTE,FILIAL,2018-06-04 00:00:00,ATIVA,None,...,ATIVIDADES IMOBILIARIAS,68,ATIVIDADES IMOBILIARIAS,ATIVIDADES IMOBILIARIAS POR CONTRATO OU COMISSAO,68.2,68.22-6,GESTAO E ADMINISTRACAO DA PROPRIEDADE IMOBILIARIA,68.22-6/00,GESTAO E ADMINISTRACAO DA PROPRIEDADE IMOBILIARIA,2026-04-13 05:46:14.493801000
1,6067460000385,IECLB - PAROQUIA APOSTOLO TIAGO,COMUNIDADE EVANGELICA LUTERANA DO BAIRRO AMIZADE,2004-01-09 00:00:00,SC,SUL,FILIAL,2004-10-23 00:00:00,ATIVA,None,...,OUTRAS ATIVIDADES DE SERVICOS,94,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS NAO ES...,94.9,94.91-0,ATIVIDADES DE ORGANIZACOES RELIGIOSAS,94.91-0/00,ATIVIDADES DE ORGANIZACOES RELIGIOSAS OU FILOS...,2026-04-13 05:46:14.493801000
2,10761012000273,"CALLADO, PETRIN, PAES E CEZAR ADVOGADOS",NaN,2019-02-07 00:00:00,SP,SUDESTE,FILIAL,2019-02-07 00:00:00,ATIVA,None,...,"ATIVIDADES PROFISSIONAIS, CIENTIFICAS E TECNICAS",69,"ATIVIDADES JURIDICAS, DE CONTABILIDADE E DE AU...",ATIVIDADES JURIDICAS,69.1,69.11-7,"ATIVIDADES JURIDICAS, EXCETO CARTORIOS",69.11-7/01,SERVICOS ADVOCATICIOS,2026-04-13 05:46:14.493801000
3,8240645000103,COMERCIAL DE COMBUSTIVEIS AEROPORTO LTDA,NaN,2006-08-14 00:00:00,RS,SUL,MATRIZ,2006-08-14 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,COMERCIO VAREJISTA DE COMBUSTIVEIS PARA VEICUL...,47.3,47.31-8,COMERCIO VAREJISTA DE COMBUSTIVEIS PARA VEICUL...,47.31-8/00,COMERCIO VAREJISTA DE COMBUSTIVEIS PARA VEICUL...,2026-04-13 05:46:14.493801000
4,24209324000100,AGENCIA HAACK DE FOTOGRAFIA LTDA,AGENCIA HAACK,2016-02-19 00:00:00,BA,NORDESTE,MATRIZ,2016-02-19 00:00:00,ATIVA,None,...,"ATIVIDADES PROFISSIONAIS, CIENTIFICAS E TECNICAS",74,"OUTRAS ATIVIDADES PROFISSIONAIS, CIENTIFICAS E...",ATIVIDADES FOTOGRAFICAS E SIMILARES,74.2,74.20-0,ATIVIDADES FOTOGRAFICAS E SIMILARES,74.20-0/01,"ATIVIDADES DE PRODUCAO DE FOTOGRAFIAS, EXCETO ...",2026-04-13 05:46:14.493801000
5,18209233000164,CONFIABIL CONTABILIDADE E CONSULTORIA LTDA,CONFIABIL,2013-05-28 00:00:00,RS,SUL,MATRIZ,2013-05-28 00:00:00,ATIVA,None,...,"ATIVIDADES PROFISSIONAIS, CIENTIFICAS E TECNICAS",69,"ATIVIDADES JURIDICAS, DE CONTABILIDADE E DE AU...","ATIVIDADES DE CONTABILIDADE, CONSULTORIA E AUD...",69.2,69.20-6,"ATIVIDADES DE CONTABILIDADE, CONSULTORIA E AUD...",69.20-6/01,ATIVIDADES DE CONTABILIDADE,2026-04-13 05:46:14.493801000
6,62186635000182,PHAROS COMUNICACAO & BUSINESS LTDA,PHAROS,2025-08-12 00:00:00,SP,SUDESTE,MATRIZ,2025-08-12 00:00:00,ATIVA,None,...,"ATIVIDADES PROFISSIONAIS, CIENTIFICAS E TECNICAS",73,PUBLICIDADE E PESQUISA DE MERCADO,PUBLICIDADE,73.1,73.19-0,ATIVIDADES DE PUBLICIDADE NAO ESPECIFICADAS AN...,73.19-0/03,MARKETING DIRETO,2026-04-13 05:46:14.493801000
7,56111762000110,ELEICAO 2024 DAVIDSON CARDOSO PEREIRA VEREADOR,NaN,2024-07-26 00:00:00,MG,SUDESTE,MATRIZ,2024-12-31 00:00:00,BAIXADA,None,...,OUTRAS ATIVIDADES DE SERVICOS,94,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS NAO ES...,94.9,94.92-8,ATIVIDADES DE ORGANIZACOES POLITICAS,94.92-8/00,ATIVIDADES DE ORGANIZACOES POLITICAS,2026-04-13 05:46:14.493801000
8,5708151000112,PARTIDO DEMOCRATICO TRABALHISTA - PORTO VELHO ...,PDT - PORTO VELHO,1985-03-19 00:00:00,RO,NORTE,MATRIZ,2019-08-27 00:00:00,ATIVA,None,...,OUTRAS ATIVIDADES DE SERVICOS,94,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS NAO ES...,94.9,94.92-8,ATIVIDADES DE ORGANIZACOES POLITICAS,94.92-8/00,ATIVIDADES DE ORGANIZACOES POLITICAS,2026-04-13 05:46:14.493801000
9,36656199000158,36.656.199 MOACIR SILVA SIMOES RAMOS,NaN,2020-03-12 00:00:00,BA,NORDESTE,MATRIZ,2025-01-30 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,COMERCIO VAREJISTA DE EQUIPAMENTOS DE INFORMAT...,47.5,47.51-2,COMERCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,47.51-2/01,COMERCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,2026-04-13 05:46:14.493801000

Arquivo: ../data/03-silver/despesa_enriquecida.parquet

Shape: (206077, 41)

Colunas:
dt_geracao                   datetime64[us]
hh_geracao                              str
aa_exercicio                          int64
tp_despesa                              str
cd_tp_esfera_partidaria                 str
ds_tp_esfera_partidaria                 str
sg_uf                                   str
cd_municipio                            str
nm_municipio                            str
nr_zona                               int64
cd_cnpj_prestador_conta                 str
sg_partido                              str
nm_partido                              str
cd_tp_documento                         str
ds_tp_documento                         str
nr_documento                            str
aa_aidf                               int64
nr_aidf                                 str
cd_tp_fornecedor                        str
ds_tp_fornecedor                        str
cd_cpf_cnpj_fornecedor                  str
nm_fornecedor                           str
ds_gasto                                str
dt_pagamento                 datetime64[us]
vl_gasto                            float64
vl_pagamento                        float64
vl_documento                        float64
cd_fonte_despesa                        str
ds_fonte_despesa                        str
sq_despesa                            int64
nm_razao_social                         str
nm_fantasia                             str
is_cnpj_enriquecido                    bool
tp_gasto                                str
tp_classificacao_origem                 str
in_despesa_administrativa              bool
in_despesa_finalistica                 bool
in_despesa_indefinida                  bool
vl_despesa_administrativa           float64
vl_despesa_finalistica              float64
vl_despesa_indefinida               float64
dtype: object

Amostra aleatória:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nm_fantasia,is_cnpj_enriquecido,tp_gasto,tp_classificacao_origem,in_despesa_administrativa,in_despesa_finalistica,in_despesa_indefinida,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida
0,2026-04-25,16:26:12,2025,NaN,4,MUNICIPAL,SP,7057,SANTO ANDRE,-1,...,NaN,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.00,0.0,0.0
1,2026-04-25,16:23:25,2025,A,1,DISTRITAL,DF,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,0.00,0.0,0.0
2,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,601.28,0.0,0.0
3,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,19.69,0.0,0.0
4,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,101.31,0.0,0.0
5,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PT.,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,113.90,0.0,0.0
6,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,179.30,0.0,0.0
7,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PDT DIRETORIO REGIONAL DA PARAIBA,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,25400.00,0.0,0.0
8,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,70000.00,0.0,0.0
9,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NOVO DIRETORIO ESTADUAL - PB,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,7299.00,0.0,0.0

TXT salvo em: ../data/05-output/notebooks/03-SILVER_despesa.txt
TXT salvo em: ../data/05-output/notebooks/03-SILVER_classificacao_despesa.txt
TXT salvo em: ../data/05-output/notebooks/03-SILVER_receita.txt
TXT salvo em: ../data/05-output/notebooks/03-SILVER_receita_enriquecida.txt
TXT salvo em: ../data/05-output/notebooks/03-SILVER_cnpj.txt
TXT salvo em: ../data/05-output/notebooks/03-SILVER_despesa_enriquecida.txt


 ==================================================
	 Verificando arquivos GOLD
 ==================================================

Arquivo: ../data/04-gold/partido_ano_despesa.parquet

Shape: (34, 11)

Colunas:
sg_partido                        str
aa_exercicio                    int64
vl_despesa_total              float64
vl_despesa_administrativa     float64
vl_despesa_finalistica        float64
vl_despesa_indefinida         float64
qtd_fornecedores_unicos         int64
pct_despesa_administrativa    float64
pct_despesa_finalistica       float64
pct_despesa_indefinida        float64
ticket_medio_despesa          float64
dtype: object

Amostra aleatória:

,sg_partido,aa_exercicio,vl_despesa_total,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida,qtd_fornecedores_unicos,pct_despesa_administrativa,pct_despesa_finalistica,pct_despesa_indefinida,ticket_medio_despesa
0,AVANTE,2025,2.188460e+07,9.806308e+06,0.0,4566747.76,277,44.809166,0.0,20.867401,79005.784260
1,CIDADANIA,2025,4.106778e+06,2.814477e+06,0.0,827583.21,288,68.532484,0.0,20.151643,14259.645451
2,MOBILIZA,2025,1.970976e+05,1.964242e+05,0.0,673.40,12,99.658342,0.0,0.341658,16424.800833
3,PC DO B,2025,2.451140e+07,1.013933e+07,0.0,4998120.07,630,41.365773,0.0,20.391003,38906.981460
4,PCO,2025,0.000000e+00,0.000000e+00,0.0,0.00,0,NaN,NaN,NaN,NaN
5,PDT,2025,5.910273e+07,2.970722e+07,0.0,16019250.72,933,50.263711,0.0,27.104080,63346.974502
6,PODE,2025,6.724362e+07,3.251337e+07,0.0,17938500.63,874,48.351602,0.0,26.676880,76937.784794
7,PP,2025,5.041076e+07,3.451222e+07,0.0,6799391.01,1213,68.462010,0.0,13.487976,41558.744938
8,PRTB,2025,0.000000e+00,0.000000e+00,0.0,0.00,0,NaN,NaN,NaN,NaN
9,PT,2025,2.261059e+08,1.086025e+08,0.0,52077272.16,3892,48.031706,0.0,23.032245,58095.049263

Arquivo: ../data/04-gold/partido_ano_receita.parquet

Shape: (34, 10)

Colunas:
sg_partido                   str
aa_exercicio               int64
vl_receita_total         float64
vl_receita_publica       float64
vl_receita_privada       float64
vl_receita_partidaria    float64
qtd_doadores_unicos        int64
pct_receita_publica      float64
pct_receita_privada      float64
ticket_medio_receita     float64
dtype: object

Amostra aleatória:

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AGIR,2025,1.207855e+06,0.000000e+00,716425.63,4.679866e+05,56,0.000000,59.313878,2.156884e+04
1,AVANTE,2025,5.362063e+07,2.944308e+07,260244.61,1.169648e+07,41,54.909980,0.485344,1.307820e+06
2,CIDADANIA,2025,1.175145e+07,3.815505e+06,501646.01,7.429742e+06,79,32.468366,4.268799,1.487526e+05
3,PL,2025,4.354022e+08,2.086250e+08,40965912.74,1.419754e+08,741,47.915465,9.408751,5.875874e+05
4,PP,2025,1.606949e+08,5.680477e+07,3478597.68,8.376226e+07,1437,35.349449,2.164722,1.118267e+05
5,PSOL,2025,2.431282e+08,2.090511e+08,685627.79,3.338911e+07,127,85.983917,0.282003,1.914395e+06
6,PT,2025,3.664338e+08,1.529199e+08,33868524.01,1.792951e+08,26006,41.731939,9.242741,1.409036e+04
7,PTB,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
8,UNIAO,2025,1.642331e+08,0.000000e+00,558854.50,1.626579e+08,334,0.000000,0.340281,4.917158e+05
9,UP,2025,6.243870e+03,0.000000e+00,6243.87,0.000000e+00,37,0.000000,100.000000,1.687532e+02

TXT salvo em: ../data/05-output/notebooks/04-GOLD_partido_ano_despesa.txt
TXT salvo em: ../data/05-output/notebooks/04-GOLD_partido_ano_receita.txt

In [4]:
from IPython.display import display
import duckdb

for file in PARQUET_SILVER_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        LIMIT 100
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    display(df.head())

Arquivo: ../data/03-silver/classificacao_despesa.parquet

Shape: (100, 2)

Colunas:
nm_despesa    str
tp_gasto      str
dtype: object

Amostra:

                                          nm_despesa        tp_gasto
0  DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...  ADMINISTRATIVO
1  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
2  TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...  ADMINISTRATIVO
3  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
4  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...     FINALÍSTICO

Arquivo: ../data/03-silver/cnpj.parquet

Shape: (100, 28)

Colunas:
cd_cnpj                       str
nm_razao_social               str
nm_fantasia                   str
dt_abertura                   str
ed_uf                         str
nm_regiao_politica            str
nm_tipo_estabelecimento       str
dt_situacao_cadastral         str
nm_situacao_cadastral         str
dt_sit_especial            object
nm_situacao_especial       object
cd_natureza_juridica          str
nm_natureza_juridica          str
nm_porte                      str
vl_capital_social             str
cd_cnae                       str
in_principal                  str
cd_nivel1_secao               str
nm_nivel1_secao               str
cd_nivel2_divisao             str
nm_nivel2_divisao             str
nm_nivel3_grupo               str
cd_nivel3_grupo               str
cd_nivel4_classe              str
nm_nivel4_classe              str
cd_nivel5_subclasse           str
nm_nivel5_subclasse           str
dt_atualizacao_pj_rfb         str
dtype: object

Amostra:

,cd_cnpj,nm_razao_social,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,87537000130,COMERCIAL MALLET LTDA,NaN,1994-06-13 00:00:00,SC,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,46,"COMERCIO POR ATACADO, EXCETO VEICULOS AUTOMOTO...",COMERCIO ATACADISTA DE PRODUTOS DE CONSUMO NAO...,46.4,46.42-7,COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E ...,46.42-7/01,COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E ...,2026-04-13 05:46:14.493801000
1,124153000140,EMBALAGENS T 2 LTDA,NaN,1994-07-27 00:00:00,GO,CENTRO-OESTE,MATRIZ,2005-01-08 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,"COMERCIO VAREJISTA DE ARTIGOS CULTURAIS, RECRE...",47.6,47.61-0,"COMERCIO VAREJISTA DE LIVROS, JORNAIS, REVISTA...",47.61-0/03,COMERCIO VAREJISTA DE ARTIGOS DE PAPELARIA,2026-04-13 05:46:14.493801000
2,165731000197,FACILITY TOUR AGENCIA DE TURISMO LTDA,FACILITY TOUR,1994-08-16 00:00:00,SP,SUDESTE,MATRIZ,2004-04-24 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000
3,370353000183,PARANOA HOTEIS E TURISMO LTDA,NaN,1974-01-14 00:00:00,DF,CENTRO-OESTE,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ALOJAMENTO E ALIMENTACAO,55,ALOJAMENTO,HOTEIS E SIMILARES,55.1,55.10-8,HOTEIS E SIMILARES,55.10-8/01,HOTEIS,2026-04-13 05:46:14.493801000
4,373580000162,CYPRESS TURISMO LTDA,CYPRESS TURISMO,1994-12-30 00:00:00,RS,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000

Arquivo: ../data/03-silver/despesa.parquet

Shape: (100, 30)

Colunas:
dt_geracao                 datetime64[us]
hh_geracao                            str
aa_exercicio                        int64
tp_despesa                         object
cd_tp_esfera_partidaria               str
ds_tp_esfera_partidaria               str
sg_uf                                 str
cd_municipio                          str
nm_municipio                          str
nr_zona                             int64
cd_cnpj_prestador_conta               str
sg_partido                            str
nm_partido                            str
cd_tp_documento                    object
ds_tp_documento                    object
nr_documento                       object
aa_aidf                             int64
nr_aidf                               str
cd_tp_fornecedor                   object
ds_tp_fornecedor                   object
cd_cpf_cnpj_fornecedor             object
nm_fornecedor                      object
ds_gasto                           object
dt_pagamento               datetime64[us]
vl_gasto                          float64
vl_pagamento                      float64
vl_documento                      float64
cd_fonte_despesa                      str
ds_fonte_despesa                   object
sq_despesa                          int64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
1,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
2,2026-04-25,16:26:12,2025,None,2,ESTADUAL,CE,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
3,2026-04-25,16:26:12,2025,None,2,ESTADUAL,MS,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
4,2026-04-25,16:26:12,2025,None,2,ESTADUAL,SP,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1

Arquivo: ../data/03-silver/receita.parquet

Shape: (100, 38)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                              object
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio,ind_dt_receita_nula
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,None,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00,2025,False
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,None,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00,2025,False
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,None,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00,2025,False
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,None,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00,2025,False
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,None,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07,2025,False

In [5]:
from IPython.display import display
import duckdb

for file in PARQUET_GOLD_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        LIMIT 100
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    display(df.head())

Arquivo: ../data/04-gold/despesa_enriquecida.parquet

Shape: (100, 41)

Colunas:
dt_geracao                   datetime64[us]
hh_geracao                              str
aa_exercicio                          int64
tp_despesa                           object
cd_tp_esfera_partidaria                 str
ds_tp_esfera_partidaria                 str
sg_uf                                   str
cd_municipio                            str
nm_municipio                            str
nr_zona                               int64
cd_cnpj_prestador_conta                 str
sg_partido                              str
nm_partido                              str
cd_tp_documento                      object
ds_tp_documento                      object
nr_documento                         object
aa_aidf                               int64
nr_aidf                                 str
cd_tp_fornecedor                     object
ds_tp_fornecedor                     object
cd_cpf_cnpj_fornecedor               object
nm_fornecedor                        object
ds_gasto                                str
dt_pagamento                 datetime64[us]
vl_gasto                            float64
vl_pagamento                        float64
vl_documento                        float64
cd_fonte_despesa                        str
ds_fonte_despesa                     object
sq_despesa                            int64
nm_razao_social                      object
nm_fantasia                          object
is_cnpj_enriquecido                    bool
tp_gasto                                str
tp_classificacao_origem                 str
in_despesa_administrativa              bool
in_despesa_finalistica                 bool
in_despesa_indefinida                  bool
vl_despesa_administrativa           float64
vl_despesa_finalistica              float64
vl_despesa_indefinida               float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nm_fantasia,is_cnpj_enriquecido,tp_gasto,tp_classificacao_origem,in_despesa_administrativa,in_despesa_finalistica,in_despesa_indefinida,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida
0,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
1,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
2,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
3,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
4,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0

Arquivo: ../data/04-gold/partido_ano_despesa.parquet

Shape: (34, 11)

Colunas:
sg_partido                        str
aa_exercicio                    int64
vl_despesa_total              float64
vl_despesa_administrativa     float64
vl_despesa_finalistica        float64
vl_despesa_indefinida         float64
qtd_fornecedores_unicos         int64
pct_despesa_administrativa    float64
pct_despesa_finalistica       float64
pct_despesa_indefinida        float64
ticket_medio_despesa          float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_despesa_total,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida,qtd_fornecedores_unicos,pct_despesa_administrativa,pct_despesa_finalistica,pct_despesa_indefinida,ticket_medio_despesa
0,AGIR,2025,873771.32,685084.32,0.0,188687.00,37,78.405448,0.0,21.594552,23615.441081
1,AVANTE,2025,21884602.24,9806307.71,0.0,4566747.76,277,44.809166,0.0,20.867401,79005.784260
2,CIDADANIA,2025,4106777.89,2814476.88,0.0,827583.21,288,68.532484,0.0,20.151643,14259.645451
3,DC,2025,1954621.90,1344255.70,0.0,609566.20,94,68.773183,0.0,31.185888,20793.850000
4,DEM,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN

Arquivo: ../data/04-gold/partido_ano_receita.parquet

Shape: (34, 10)

Colunas:
sg_partido                   str
aa_exercicio               int64
vl_receita_total         float64
vl_receita_publica       float64
vl_receita_privada       float64
vl_receita_partidaria    float64
qtd_doadores_unicos        int64
pct_receita_publica      float64
pct_receita_privada      float64
ticket_medio_receita     float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AGIR,2025,1207854.99,0.00,716425.63,467986.60,56,0.000000,59.313878,2.156884e+04
1,AVANTE,2025,53620628.37,29443076.52,260244.61,11696480.12,41,54.909980,0.485344,1.307820e+06
2,CIDADANIA,2025,11751454.30,3815505.23,501646.01,7429741.60,79,32.468366,4.268799,1.487526e+05
3,DC,2025,3523606.22,0.00,1281392.84,2234784.96,150,0.000000,36.365949,2.349071e+04
4,DEM,2025,0.00,0.00,0.00,0.00,0,NaN,NaN,NaN

Arquivo: ../data/04-gold/receita_enriquecida.parquet

Shape: (100, 48)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                              object
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
nm_razao_social                              str
nm_fantasia                                  str
is_cnpj_enriquecido                         bool
tp_receita                                   str
in_receita_publica                          bool
in_receita_privada                          bool
in_receita_partidaria                       bool
vl_receita_publica                       float64
vl_receita_privada                       float64
vl_receita_partidaria                    float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,5000.0