# Verificação rápida dos dados

In [1]:
from IPython.display import display
import duckdb

PARQUET_BRONZE_FILE_NAME = ["../data/02-bronze/classificacao_despesa.parquet",
                            "../data/02-bronze/cnpj.parquet",
                            "../data/02-bronze/despesa.parquet",
                            "../data/02-bronze/receita.parquet"
                            ]

PARQUET_SILVER_FILE_NAME = ["../data/03-silver/classificacao_despesa.parquet",
                            "../data/03-silver/cnpj.parquet",
                            "../data/03-silver/despesa.parquet",
                            "../data/03-silver/receita.parquet"
                            ]

PARQUET_GOLD_FILE_NAME = ["../data/04-gold/despesa_enriquecida.parquet",
                    "../data/04-gold/partido_ano_despesa.parquet",
                    "../data/04-gold/partido_ano_receita.parquet",
                    "../data/04-gold/receita_enriquecida.parquet"]

def verificar_dados(parquet_file_names):
    for file in parquet_file_names:
        print(f"\nArquivo: {file}")
    
        df = duckdb.sql(
            f"""
            SELECT *
            FROM read_parquet('{file}')
            USING SAMPLE 10 ROWS
            """
        ).df()
        print("\nShape:", df.shape)
        print("\nColunas:")
        print(df.dtypes)

        print("\nAmostra:")
        display(df)

## Visualiza todos os dados

In [9]:
print("="*50, "\n\t Verificando arquivos BRONZE \n","="*50)
verificar_dados(PARQUET_BRONZE_FILE_NAME)

print("\n\n", "="*50, "\n\t Verificando arquivos SILVER \n", "="*50)
verificar_dados(PARQUET_SILVER_FILE_NAME)

print("\n\n", "="*50, "\n\t Verificando arquivos GOLD \n", "="*50)
verificar_dados(PARQUET_GOLD_FILE_NAME)

==================================================
	 Verificando arquivos BRONZE
 ==================================================

Arquivo: ../data/02-bronze/classificacao_despesa.parquet

Shape: (10, 2)

Colunas:
DESPESA                                                                                                                                       str
CLASSIFICACAO                                                                                                                                 str
dtype: object

Amostra:

,DESPESA,CLASSIFICACAO
0,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,ADMINISTRATIVO
1,ASSINATURAS E AQUISICOES DE PERIODICOS - ORDIN...,INDEFINIDO
2,MATERIAL DE CONSUMO - MATERIAIS IMPRESSOS - MU...,FINALÍSTICO
3,DESPESAS FINANCEIRAS - ATUALIZACAO MONETARIA D...,ADMINISTRATIVO
4,LANCHES E REFEICOES - MULHERES ...,FINALÍSTICO
5,SERVICOS TECNICO-PROFISSIONAIS - OUTROS SERVIC...,FINALÍSTICO
6,TRANSPORTES E VIAGENS - PEDAGIOS - ORDINARIAS ...,INDEFINIDO
7,SERVICOS TECNICO-PROFISSIONAIS - SERVICOS DE C...,FINALÍSTICO
8,DESPESAS COM PUBLICIDADE POR ADESIVOS - ELEITO...,FINALÍSTICO
9,DESPESAS COM CONVENCOES PARTIDARIAS - ELEITORA...,FINALÍSTICO

Arquivo: ../data/02-bronze/cnpj.parquet

Shape: (10, 28)

Colunas:
cd_cnpj                       str
nm_empresarial                str
nm_fantasia                   str
dt_abertura                   str
ed_uf                         str
nm_regiao_politica            str
nm_tipo_estabelecimento       str
dt_situacao_cadastral         str
nm_situacao_cadastral         str
dt_sit_especial            object
nm_situacao_especial       object
cd_natureza_juridica          str
nm_natureza_juridica          str
nm_porte                      str
vl_capital_social             str
cd_cnae                       str
in_principal                  str
cd_nivel1_secao               str
nm_nivel1_secao               str
cd_nivel2_divisao             str
nm_nivel2_divisao             str
nm_nivel3_grupo               str
cd_nivel3_grupo               str
cd_nivel4_classe              str
nm_nivel4_classe              str
cd_nivel5_subclasse           str
nm_nivel5_subclasse           str
dt_atualizacao_pj_rfb         str
dtype: object

Amostra:

,cd_cnpj,nm_empresarial,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,313998,BANCO DO BRASIL SA,EMPRESA FARRAPOS - PORTO ALEGRE (RS),2000-11-23 00:00:00,RS,SUL,Filial,2005-11-03 00:00:00,Ativa,None,...,"ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS ...",64,ATIVIDADES DE SERVIÇOS FINANCEIROS,Intermediação monetária - depósitos à vista,64.2,64.22-1,"Bancos múltiplos, com carteira comercial",64.22-1/00,"Bancos múltiplos, com carteira comercial",2026-04-13 05:46:14.493801000
1,4127889000123,PLANA - CONSTRUCOES E SERVICOS LTDA,MARMORARIA PLANALTO,2000-11-08 00:00:00,DF,CENTRO-OESTE,Matriz,2008-12-31 00:00:00,Ativa,None,...,CONSTRUÇÃO,41,CONSTRUÇÃO DE EDIFÍCIOS,Construção de edifícios,41.2,41.20-4,Construção de edifícios,41.20-4/00,Construção de edifícios,2026-04-13 05:46:14.493801000
2,12330520000141,KIKA - COMERCIO E LOCACAO DE MATERIAIS PARA FE...,KIKA - LOCACAO DE MATERIAIS PARA FESTAS,2010-07-30 00:00:00,DF,CENTRO-OESTE,Matriz,2010-07-30 00:00:00,Ativa,None,...,ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEME...,77,ALUGUÉIS NÃO IMOBILIÁRIOS E GESTÃO DE ATIVOS I...,Aluguel de objetos pessoais e domésticos,77.2,77.29-2,Aluguel de objetos pessoais e domésticos não e...,77.29-2/02,"Aluguel de móveis, utensílios e aparelhos de u...",2026-04-13 05:46:14.493801000
3,35773464000115,TALIMPO MATERIAIS PARA CONDOMINIOS LTDA,NaN,1989-08-09 00:00:00,RJ,SUDESTE,Matriz,2004-08-21 00:00:00,Ativa,None,...,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,47,COMÉRCIO VAREJISTA,Comércio varejista não especializado,47.1,47.12-1,"Comércio varejista de mercadorias em geral, co...",47.12-1/00,"Comércio varejista de mercadorias em geral, co...",2026-04-13 05:46:14.493801000
4,47627554000187,B C MORAIS MARIANO LTDA,YOUW PRODUTORA,2022-08-18 00:00:00,TO,NORTE,Matriz,2022-08-18 00:00:00,Ativa,None,...,"ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS",73,PUBLICIDADE E PESQUISA DE MERCADO,Publicidade,73.1,73.11-4,Agências de publicidade,73.11-4/00,Agências de publicidade,2026-04-13 05:46:14.493801000
5,58719801000191,BM12 SERVICOS CORPORATIVOS E TREINAMENTOS LTDA,BM12,2025-01-09 00:00:00,MG,SUDESTE,Matriz,2025-01-09 00:00:00,Ativa,None,...,EDUCAÇÃO,85,EDUCAÇÃO,Outras atividades de ensino,85.9,85.99-6,Atividades de ensino não especificadas anterio...,85.99-6/04,Treinamento em desenvolvimento profissional e ...,2026-04-13 05:46:14.493801000
6,93209765055361,WMS SUPERMERCADOS DO BRASIL LTDA.,ATACADAO,2023-08-03 00:00:00,BA,NORDESTE,Filial,2023-08-03 00:00:00,Ativa,None,...,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,47,COMÉRCIO VAREJISTA,Comércio varejista não especializado,47.1,47.11-3,"Comércio varejista de mercadorias em geral, co...",47.11-3/01,"Comércio varejista de mercadorias em geral, co...",2026-04-13 05:46:14.493801000
7,53781123000173,53.781.123 ANDERSON SILVA DE OLIVEIRA,NaN,2024-02-02 00:00:00,AL,NORDESTE,Matriz,2024-02-02 00:00:00,Ativa,None,...,"TRANSPORTE, ARMAZENAGEM E CORREIO",49,TRANSPORTE TERRESTRE,Transporte rodoviário de passageiros,49.2,49.29-9,"Transporte rodoviário coletivo de passageiros,...",49.29-9/01,"Transporte rodoviário coletivo de passageiros,...",2026-04-13 05:46:14.493801000
8,74045568000165,DIRETORIO MUNICIPAL DO PT-CACERES-MT,DM/PT-CACERES-MT,1994-01-11 00:00:00,MT,CENTRO-OESTE,Matriz,2020-07-07 00:00:00,Ativa,None,...,OUTRAS ATIVIDADES DE SERVIÇOS,94,ATIVIDADES DE ORGANIZAÇÕES ASSOCIATIVAS,Atividades de organizações associativas não es...,94.9,94.92-8,Atividades de organizações políticas,94.92-8/00,Atividades de organizações políticas,2026-04-13 05:46:14.493801000
9,44353633000159,SIRLEI DE MORAES RODRIGUES,GRUPO RT VIGILANCIA E SEGURANCA,2021-11-24 00:00:00,RS,SUL,Matriz,2021-11-24 00:00:00,Ativa,None,...,ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEME...,80,"ATIVIDADES DE VIGILÂNCIA, SEGURANÇA E INVESTIG...","Atividades de vigilância, segurança privada e ...",80.1,80.11-1,Atividades de vigilância e segurança privada,80.11-1/01,Atividades de vigilância e segurança privada,2026-04-13 05:46:14.493801000

Arquivo: ../data/02-bronze/despesa.parquet

Shape: (10, 30)

Colunas:
DT_GERACAO                 str
HH_GERACAO                 str
AA_EXERCICIO               str
TP_DESPESA                 str
CD_TP_ESFERA_PARTIDARIA    str
DS_TP_ESFERA_PARTIDARIA    str
SG_UF                      str
CD_MUNICIPIO               str
NM_MUNICIPIO               str
NR_ZONA                    str
NR_CNPJ_PRESTADOR_CONTA    str
SG_PARTIDO                 str
NM_PARTIDO                 str
CD_TP_DOCUMENTO            str
DS_TP_DOCUMENTO            str
NR_DOCUMENTO               str
AA_AIDF                    str
NR_AIDF                    str
CD_TP_FORNECEDOR           str
DS_TP_FORNECEDOR           str
NR_CPF_CNPJ_FORNECEDOR     str
NM_FORNECEDOR              str
DS_GASTO                   str
DT_PAGAMENTO               str
VR_GASTO                   str
VR_PAGAMENTO               str
VR_DOCUMENTO               str
CD_FONTE_DESPESA           str
DS_FONTE_DESPESA           str
SQ_DESPESA                 str
dtype: object

Amostra:

,DT_GERACAO,HH_GERACAO,AA_EXERCICIO,TP_DESPESA,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESFERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,...,NR_CPF_CNPJ_FORNECEDOR,NM_FORNECEDOR,DS_GASTO,DT_PAGAMENTO,VR_GASTO,VR_PAGAMENTO,VR_DOCUMENTO,CD_FONTE_DESPESA,DS_FONTE_DESPESA,SQ_DESPESA
0,25/04/2026,16:26:12,2025,#NULO#,4,Municipal,SP,6391,DUARTINA,-1,...,#NULO#,#NULO#,#NULO#,,0,0,0,-1,#NULO#,-1
1,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,07044522000134,Direção Estadual/Distrital - PT - CEARÁ,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,08/07/2025,"2854,33","2854,33","2854,33",2,Outros Recursos,-1
2,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,01307364000181,Direção Municipal/Comissão Provisória - PT - R...,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,27/06/2025,"166,46","166,46","166,46",2,Outros Recursos,-1
3,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,17311189000136,Direção Zonal - PT - Zona 11,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - OUTROS ...,05/11/2025,"147,72","147,72","147,72",2,Outros Recursos,-1
4,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,84023985000160,Direção Estadual/Distrital - PSDB - RORAIMA,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - FUNDO P...,06/06/2025,189,189,189,1,Fundo Partidário,-1
5,25/04/2026,16:23:25,2025,D,0,Nacional,BR,-1,#NULO#,-1,...,53495793000123,Direção Estadual/Distrital - PRD - SÃO PAULO,TRANSFERÊNCIAS FINANCEIRAS EFETUADAS - FUNDO P...,06/08/2025,654000,654000,654000,1,Fundo Partidário,-1
6,25/04/2026,16:23:25,2025,G,1,Distrital,DF,-1,#NULO#,-1,...,00000000314706,BANCO DO BRASIL S/A,DESPESAS FINANCEIRAS - COMISSÕES E TARIFAS BAN...,04/08/2025,13,13,13,1,Fundo Partidário,4016052
7,25/04/2026,16:23:25,2025,G,2,Estadual,SP,-1,#NULO#,-1,...,00394460040950,MINISTERIO DA FAZENDA / SECRETARIA TESOURO NAC...,RECOLHIMENTOS AO ERÁRIO - DESPESAS COM MULTAS ...,16/12/2025,"301,4","301,4","301,4",2,Outros Recursos,4037116
8,25/04/2026,16:23:25,2025,G,2,Estadual,PR,-1,#NULO#,-1,...,18191228000171,PJ BANK PAGAMENTOS SA,ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS IMÓVE...,17/03/2025,"11779,79","11779,79","11779,79",1,Fundo Partidário,3843555
9,25/04/2026,16:23:25,2025,G,2,Estadual,RR,-1,#NULO#,-1,...,00000000000191,Banco do Brasil SA,DESPESAS FINANCEIRAS - COMISSÕES E TARIFAS BAN...,21/07/2025,10,10,10,1,Fundo Partidário,3940821

Arquivo: ../data/02-bronze/receita.parquet

Shape: (10, 36)

Colunas:
DT_GERACAO                        str
HH_GERACAO                        str
CD_TP_ESFERA_PARTIDARIA           str
DS_TP_ESPERA_PARTIDARIA           str
SG_UF                             str
CD_MUNICIPIO                      str
NM_MUNICIPIO                      str
NR_ZONA                           str
NR_CNPJ_PRESTADOR_CONTA           str
SG_PARTIDO                        str
NM_PARTIDO                        str
CD_TP_ORIGEM_DOACAO               str
DS_TP_ORIGEM_DOACAO               str
NR_CPF_CNPJ_DOADOR                str
NM_DOADOR                         str
CD_TP_ESFERA_PARTIDARIA_DOADOR    str
DS_TP_ESFERA_PARTIDARIA_DOADOR    str
SG_UF_DOADOR                      str
CD_MUNICIPIO_DOADOR               str
NM_MUNICIPIO_DOADOR               str
NR_ZONA_DOADOR                    str
SQ_CANDIDATO_DOADOR               str
NR_CANDIDATO_DOADOR               str
CD_CANDIDATO_CARGO_DOADOR         str
DS_CANDIDATO_CARGO_DOADOR         str
CD_TP_FONTE_RECURSO               str
DS_TP_FONTE_RECURSO               str
CD_TP_NATUREZA_RECURSO            str
DS_TP_NATUREZA_RECURSO            str
CD_TP_ESPECIE_RECURSO             str
DS_TP_ESPECIE_RECURSO             str
NR_RECIBO_DOACAO                  str
NR_DOCUMENTO                      str
DT_RECEITA                        str
DS_RECEITA                        str
VR_RECEITA                        str
dtype: object

Amostra:

,DT_GERACAO,HH_GERACAO,CD_TP_ESFERA_PARTIDARIA,DS_TP_ESPERA_PARTIDARIA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_CNPJ_PRESTADOR_CONTA,SG_PARTIDO,...,DS_TP_FONTE_RECURSO,CD_TP_NATUREZA_RECURSO,DS_TP_NATUREZA_RECURSO,CD_TP_ESPECIE_RECURSO,DS_TP_ESPECIE_RECURSO,NR_RECIBO_DOACAO,NR_DOCUMENTO,DT_RECEITA,DS_RECEITA,VR_RECEITA
0,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676213000138,MDB,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,3922,#NULO#,04/07/2025,CONTRIBUIÇÕES - DE PARLAMENTARES,1000
1,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1025186,1025186,11/02/2025,CONTRIBUIÇÕES - DE FILIADOS,40
2,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1034340,1034340,11/02/2025,CONTRIBUIÇÕES - DE FILIADOS,"42,35"
3,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,13405866000124,NOVO,...,Outros Recursos,0,Financeiro,0,Cartão de crédito,1037602,1037602,31/03/2025,CONTRIBUIÇÕES - DE FILIADOS,"42,35"
4,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,54956495000156,PC do B,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,171028,#NULO#,29/04/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,50
5,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,08517423000195,PL,...,Fundo Partidário,0,Financeiro,5,Ordem bancária,#NULO#,4.162.320.000.000,26/08/2025,FUNDO PARTIDÁRIO - DIREÇÃO NACIONAL - COTAS RE...,"15993430,21"
6,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,1005608,#NULO#,28/05/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,"382,28"
7,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,973428,#NULO#,20/01/2025,CONTRIBUIÇÕES - DE PARLAMENTARES,"386,87"
8,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,987243,#NULO#,08/04/2025,CONTRIBUIÇÕES - OUTRAS CONTRIBUIÇÕES,"74,57"
9,25/04/2026,16:24:44,0,Nacional,BR,#NULO#,#NULO#,#NULO#,00676262000170,PT,...,Outros Recursos,0,Financeiro,7,Transferência eletrônica,978051,#NULO#,24/02/2025,CONTRIBUIÇÕES - DE FILIADOS,25

 ==================================================
	 Verificando arquivos SILVER
 ==================================================

Arquivo: ../data/03-silver/classificacao_despesa.parquet

Shape: (10, 2)

Colunas:
nm_despesa    str
tp_gasto      str
dtype: object

Amostra:

                                          nm_despesa        tp_gasto
0  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
1  PESSOAL - PREVIDENCIA SOCIAL - ORDINARIAS     ...  ADMINISTRATIVO
2  ENERGIA ELETRICA - ORDINARIAS                 ...  ADMINISTRATIVO
3  TRIBUTOS - IPTU - ORDINARIAS                  ...  ADMINISTRATIVO
4  ALUGUEIS E CONDOMINIOS - LOCACAO DE BENS IMOVE...     FINALÍSTICO
5  TRANSPORTES E VIAGENS - PEDAGIOS - ORDINARIAS ...      INDEFINIDO
6  TRANSPORTES E VIAGENS - COMBUSTIVEIS, OLEOS E ...     FINALÍSTICO
7  OUTRAS DESPESAS GERAIS - DESPESAS ELEITORAIS  ...     FINALÍSTICO
8  SERVICOS DE LIMPEZA - DESPESAS ELEITORAIS     ...     FINALÍSTICO
9  SERVICOS TECNICO-PROFISSIONAIS - SERVICOS CONT...     FINALÍSTICO

Arquivo: ../data/03-silver/cnpj.parquet

Shape: (10, 28)

Colunas:
cd_cnpj                       str
nm_razao_social               str
nm_fantasia                   str
dt_abertura                   str
ed_uf                         str
nm_regiao_politica            str
nm_tipo_estabelecimento       str
dt_situacao_cadastral         str
nm_situacao_cadastral         str
dt_sit_especial            object
nm_situacao_especial       object
cd_natureza_juridica          str
nm_natureza_juridica          str
nm_porte                      str
vl_capital_social             str
cd_cnae                       str
in_principal                  str
cd_nivel1_secao               str
nm_nivel1_secao               str
cd_nivel2_divisao             str
nm_nivel2_divisao             str
nm_nivel3_grupo               str
cd_nivel3_grupo               str
cd_nivel4_classe              str
nm_nivel4_classe              str
cd_nivel5_subclasse           str
nm_nivel5_subclasse           str
dt_atualizacao_pj_rfb         str
dtype: object

Amostra:

,cd_cnpj,nm_razao_social,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,1486634000169,FERNANDES E AGUIAR LOCACAO E EVENTOS LTDA,GRAPHIX LOCACAO E EVENTOS,1996-08-01 00:00:00,MG,SUDESTE,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,77,ALUGUEIS NAO IMOBILIARIOS E GESTAO DE ATIVOS I...,ALUGUEL DE MAQUINAS E EQUIPAMENTOS SEM OPERADOR,77.3,77.33-1,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...,77.33-1/00,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...,2026-04-13 05:46:14.493801000
1,7680371000100,SAINT VIAGENS LTDA,NaN,2005-11-08 00:00:00,SC,SUL,MATRIZ,2005-11-08 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000
2,23540812000125,PANELINHAS DO BRASIL COZINHA E RESTAURANTE VEN...,PANELINHAS DO BRASIL VENANCIO 2000,2015-10-21 00:00:00,DF,CENTRO-OESTE,MATRIZ,2015-10-21 00:00:00,ATIVA,None,...,ALOJAMENTO E ALIMENTACAO,56,ALIMENTACAO,RESTAURANTES E OUTROS SERVICOS DE ALIMENTACAO ...,56.1,56.11-2,RESTAURANTES E OUTROS ESTABELECIMENTOS DE SERV...,56.11-2/01,RESTAURANTES E SIMILARES,2026-04-13 05:46:14.493801000
3,9461647000195,SOLUTI - SOLUCOES EM NEGOCIOS INTELIGENTES S/A,SOLUTI,2008-04-03 00:00:00,GO,CENTRO-OESTE,MATRIZ,2008-04-03 00:00:00,ATIVA,None,...,INFORMACAO E COMUNICACAO,62,ATIVIDADES DOS SERVICOS DE TECNOLOGIA DA INFOR...,ATIVIDADES DOS SERVICOS DE TECNOLOGIA DA INFOR...,62.0,62.09-1,"SUPORTE TECNICO, MANUTENCAO E OUTROS SERVICOS ...",62.09-1/00,"SUPORTE TECNICO, MANUTENCAO E OUTROS SERVICOS ...",2026-04-13 05:46:14.493801000
4,13755294000103,SUPER PC COMERCIO VAREJISTA DE ALIMENTOS LTDA,SUPER PC,2011-06-06 00:00:00,CE,NORDESTE,MATRIZ,2011-06-06 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,COMERCIO VAREJISTA NAO ESPECIALIZADO,47.1,47.12-1,"COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, CO...",47.12-1/00,"COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, CO...",2026-04-13 05:46:14.493801000
5,31646187000129,THAI RESTAURANTE LTDA,NaN,2018-10-01 00:00:00,MA,NORDESTE,MATRIZ,2018-10-01 00:00:00,ATIVA,None,...,ALOJAMENTO E ALIMENTACAO,56,ALIMENTACAO,RESTAURANTES E OUTROS SERVICOS DE ALIMENTACAO ...,56.1,56.11-2,RESTAURANTES E OUTROS ESTABELECIMENTOS DE SERV...,56.11-2/01,RESTAURANTES E SIMILARES,2026-04-13 05:46:14.493801000
6,34805069000104,V. FRANCISCO DA SILVA LTDA,PAPELARIA SANTA HELENA,1990-10-17 00:00:00,RR,NORTE,MATRIZ,2005-10-14 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,"COMERCIO VAREJISTA DE ARTIGOS CULTURAIS, RECRE...",47.6,47.61-0,"COMERCIO VAREJISTA DE LIVROS, JORNAIS, REVISTA...",47.61-0/03,COMERCIO VAREJISTA DE ARTIGOS DE PAPELARIA,2026-04-13 05:46:14.493801000
7,62397662000102,ELEICAO SUPLEMENTAR JOAO PAULO TRAVASSOS RADDI...,NaN,2025-08-26 00:00:00,PR,SUL,MATRIZ,2025-08-26 00:00:00,ATIVA,None,...,OUTRAS ATIVIDADES DE SERVICOS,94,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS NAO ES...,94.9,94.92-8,ATIVIDADES DE ORGANIZACOES POLITICAS,94.92-8/00,ATIVIDADES DE ORGANIZACOES POLITICAS,2026-04-13 05:46:14.493801000
8,4572445000105,ZILMAR IUNG DA SILVA,NaN,2001-07-26 00:00:00,RS,SUL,MATRIZ,2026-03-05 00:00:00,BAIXADA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,"COMERCIO VAREJISTA DE PRODUTOS ALIMENTICIOS, B...",47.2,47.22-9,COMERCIO VAREJISTA DE CARNES E PESCADOS - ACOU...,47.22-9/01,COMERCIO VAREJISTA DE CARNES - ACOUGUES,2026-04-13 05:46:14.493801000
9,56726520000130,ELEICAO 2024 ANGELO MARCIO DELLA ROVERE VEREADOR,NaN,2024-08-14 00:00:00,MT,CENTRO-OESTE,MATRIZ,2024-12-31 00:00:00,BAIXADA,None,...,OUTRAS ATIVIDADES DE SERVICOS,94,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS,ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS NAO ES...,94.9,94.92-8,ATIVIDADES DE ORGANIZACOES POLITICAS,94.92-8/00,ATIVIDADES DE ORGANIZACOES POLITICAS,2026-04-13 05:46:14.493801000

Arquivo: ../data/03-silver/despesa.parquet

Shape: (10, 30)

Colunas:
dt_geracao                 datetime64[us]
hh_geracao                            str
aa_exercicio                        int64
tp_despesa                            str
cd_tp_esfera_partidaria               str
ds_tp_esfera_partidaria               str
sg_uf                                 str
cd_municipio                          str
nm_municipio                          str
nr_zona                             int64
cd_cnpj_prestador_conta               str
sg_partido                            str
nm_partido                            str
cd_tp_documento                       str
ds_tp_documento                       str
nr_documento                          str
aa_aidf                             int64
nr_aidf                               str
cd_tp_fornecedor                      str
ds_tp_fornecedor                      str
cd_cpf_cnpj_fornecedor                str
nm_fornecedor                         str
ds_gasto                              str
dt_pagamento               datetime64[us]
vl_gasto                          float64
vl_pagamento                      float64
vl_documento                      float64
cd_fonte_despesa                      str
ds_fonte_despesa                      str
sq_despesa                          int64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,NaN,4,MUNICIPAL,MG,4193,CACHOEIRA DE MINAS,-1,...,NaN,NaN,NaN,NaT,0.00,0.00,0.00,-1,NaN,-1
1,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,80674633000114,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - T...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-06-04,39.38,39.38,39.38,2,OUTROS RECURSOS,-1
2,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,92410661000103,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - P...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-01-13,55.52,55.52,55.52,2,OUTROS RECURSOS,-1
3,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,92518190000151,DIRECAO MUNICIPAL/COMISSAO PROVISORIA - PT - V...,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-05-20,46.26,46.26,46.26,2,OUTROS RECURSOS,-1
4,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,79306908000188,DIRECAO ESTADUAL/DISTRITAL - PT - SANTA CATARINA,TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...,2025-09-29,219.58,219.58,219.58,2,OUTROS RECURSOS,-1
5,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,08808169000184,DIRECAO ESTADUAL/DISTRITAL - PL - CEARA,TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...,2025-12-19,120000.00,120000.00,120000.00,1,FUNDO PARTIDARIO,-1
6,2026-04-25,16:23:25,2025,G,2,ESTADUAL,PI,-1,NaN,-1,...,06840748000189,EQUATORIAL PIAUI DISTRIBUIDORA DE ENERGIA S.A,ENERGIA ELETRICA - ORDINARIAS,2025-04-25,396.40,396.40,396.40,1,FUNDO PARTIDARIO,4008897
7,2026-04-25,16:23:25,2025,G,2,ESTADUAL,GO,-1,NaN,-1,...,05850850000100,FOSTIORI PESQUISA DIAGNOSTICO E MARKETING LTDA,SERVICOS TECNICO-PROFISSIONAIS - OUTROS SERVIC...,2025-10-09,48000.00,48000.00,48000.00,1,FUNDO PARTIDARIO,4059024
8,2026-04-25,16:23:25,2025,G,2,ESTADUAL,BA,-1,NaN,-1,...,00000000389382,BCO DO BRASIL S/A,DESPESAS FINANCEIRAS - COMISSOES E TARIFAS BAN...,2025-12-05,139.20,139.20,139.20,2,OUTROS RECURSOS,4038952
9,2026-04-25,16:23:25,2025,G,2,ESTADUAL,PE,-1,NaN,-1,...,09480880000115,BRASLUSO TURISMO LTDA,TRANSPORTES E VIAGENS - PASSAGENS AEREAS - ORD...,2025-05-08,1098.93,1098.93,1098.93,1,FUNDO PARTIDARIO,3956051

Arquivo: ../data/03-silver/receita.parquet

Shape: (10, 38)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                 object
ds_candidato_cargo_doador                 object
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                                 str
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio,ind_dt_receita_nula
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1026681,NaN,2025-01-15,CONTRIBUICOES - DE FILIADOS,40.00,2025,False
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1038438,NaN,2025-03-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1039757,1039757,2025-03-14,CONTRIBUICOES - DE FILIADOS,42.35,2025,False
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,0,CARTAO DE CREDITO,1028589,1028589,2025-02-11,CONTRIBUICOES - DE FILIADOS,39.75,2025,False
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1033568,NaN,2025-02-11,CONTRIBUICOES - DE FILIADOS,254.10,2025,False
5,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,175695,NaN,2025-07-24,CONTRIBUICOES - OUTRAS CONTRIBUICOES,250.00,2025,False
6,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,73282907000164,PSTU,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,19819,19819,2025-12-04,DOACOES PARA MANUTENCAO DO PARTIDO - PESSOAS F...,670.00,2025,False
7,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1014086,NaN,2025-06-16,CONTRIBUICOES - DE FILIADOS,30.00,2025,False
8,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,971585,NaN,2025-01-03,CONTRIBUICOES - OUTRAS CONTRIBUICOES,56.17,2025,False
9,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1033792,NaN,2025-09-30,CONTRIBUICOES - DE FILIADOS,40.00,2025,False

 ==================================================
	 Verificando arquivos GOLD
 ==================================================

Arquivo: ../data/04-gold/despesa_enriquecida.parquet

Shape: (10, 41)

Colunas:
dt_geracao                   datetime64[us]
hh_geracao                              str
aa_exercicio                          int64
tp_despesa                              str
cd_tp_esfera_partidaria                 str
ds_tp_esfera_partidaria                 str
sg_uf                                   str
cd_municipio                            str
nm_municipio                            str
nr_zona                               int64
cd_cnpj_prestador_conta                 str
sg_partido                              str
nm_partido                              str
cd_tp_documento                      object
ds_tp_documento                      object
nr_documento                            str
aa_aidf                               int64
nr_aidf                                 str
cd_tp_fornecedor                        str
ds_tp_fornecedor                        str
cd_cpf_cnpj_fornecedor                  str
nm_fornecedor                           str
ds_gasto                                str
dt_pagamento                 datetime64[us]
vl_gasto                            float64
vl_pagamento                        float64
vl_documento                        float64
cd_fonte_despesa                        str
ds_fonte_despesa                        str
sq_despesa                            int64
nm_razao_social                         str
nm_fantasia                             str
is_cnpj_enriquecido                    bool
tp_gasto                                str
tp_classificacao_origem                 str
in_despesa_administrativa              bool
in_despesa_finalistica                 bool
in_despesa_indefinida                  bool
vl_despesa_administrativa           float64
vl_despesa_finalistica              float64
vl_despesa_indefinida               float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nm_fantasia,is_cnpj_enriquecido,tp_gasto,tp_classificacao_origem,in_despesa_administrativa,in_despesa_finalistica,in_despesa_indefinida,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida
0,2026-04-25,16:26:12,2025,NaN,4,MUNICIPAL,TO,9685,AUGUSTINOPOLIS,-1,...,NaN,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.00,0.0,0.0
1,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,46.26,0.0,0.0
2,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PT DIRETORIO MUNICIPAL DE RIBEIRAO PRETO,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,119.55,0.0,0.0
3,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,P T DE TOLEDO,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,35.79,0.0,0.0
4,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,49.04,0.0,0.0
5,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,19.69,0.0,0.0
6,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PT - DIRETORIO REGIONAL NO ESPIRITO SANTO,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,134.66,0.0,0.0
7,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,PT.,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,334.81,0.0,0.0
8,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,NaN,False,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,461.00,0.0,0.0
9,2026-04-25,16:23:25,2025,D,0,NACIONAL,BR,-1,NaN,-1,...,REDE SUSTENTABILIDADE BAHIA,True,ADMINISTRATIVO,LOOKUP_EXATO,True,False,False,17601.01,0.0,0.0

Arquivo: ../data/04-gold/partido_ano_despesa.parquet

Shape: (10, 11)

Colunas:
sg_partido                        str
aa_exercicio                    int64
vl_despesa_total              float64
vl_despesa_administrativa     float64
vl_despesa_finalistica        float64
vl_despesa_indefinida         float64
qtd_fornecedores_unicos         int64
pct_despesa_administrativa    float64
pct_despesa_finalistica       float64
pct_despesa_indefinida        float64
ticket_medio_despesa          float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_despesa_total,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida,qtd_fornecedores_unicos,pct_despesa_administrativa,pct_despesa_finalistica,pct_despesa_indefinida,ticket_medio_despesa
0,DEMOCRATA,2025,0.000000e+00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN
1,MDB,2025,8.528770e+07,46555980.08,0.0,12769394.47,1518,54.586979,0.0,14.972140,56184.256706
2,MOBILIZA,2025,1.970976e+05,196424.21,0.0,673.40,12,99.658342,0.0,0.341658,16424.800833
3,PC DO B,2025,2.451140e+07,10139329.33,0.0,4998120.07,630,41.365773,0.0,20.391003,38906.981460
4,PL,2025,1.930613e+08,92686798.44,0.0,27540340.98,2303,48.009004,0.0,14.265077,83830.344620
5,PODE,2025,6.724362e+07,32513369.42,0.0,17938500.63,874,48.351602,0.0,26.676880,76937.784794
6,PSTU,2025,1.429225e+06,923728.67,0.0,489534.77,85,64.631418,0.0,34.251753,16814.416941
7,PTB,2025,0.000000e+00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN
8,REDE,2025,1.408469e+07,7638723.79,0.0,4742285.03,609,54.234227,0.0,33.669781,23127.573136
9,REPUBLICANOS,2025,7.152582e+07,34897839.53,0.0,6287534.00,1308,48.790547,0.0,8.790579,54683.349901

Arquivo: ../data/04-gold/partido_ano_receita.parquet

Shape: (10, 10)

Colunas:
sg_partido                   str
aa_exercicio               int64
vl_receita_total         float64
vl_receita_publica       float64
vl_receita_privada       float64
vl_receita_partidaria    float64
qtd_doadores_unicos        int64
pct_receita_publica      float64
pct_receita_privada      float64
ticket_medio_receita     float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AVANTE,2025,5.362063e+07,2.944308e+07,260244.61,1.169648e+07,41,54.909980,0.485344,1.307820e+06
1,DEM,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
2,DEMOCRATA,2025,7.200533e+04,0.000000e+00,31680.33,4.032000e+04,8,0.000000,43.997201,9.000666e+03
3,PC DO B,2025,3.331525e+07,1.982971e+07,3480874.39,9.982024e+06,2145,59.521410,10.448290,1.553159e+04
4,PL,2025,4.354022e+08,2.086250e+08,40965912.74,1.419754e+08,741,47.915465,9.408751,5.875874e+05
5,PSB,2025,8.264136e+07,5.370288e+07,2027596.67,2.402719e+07,692,64.983059,2.453489,1.194239e+05
6,PSC,2025,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0,NaN,NaN,NaN
7,PSD,2025,2.469565e+08,9.135067e+07,1331629.89,1.352106e+08,688,36.990593,0.539216,3.589484e+05
8,SDD,2025,5.249612e+07,1.938335e+07,2217393.08,2.975792e+07,82,36.923395,4.223918,6.401965e+05
9,UNIAO,2025,1.642331e+08,0.000000e+00,558854.50,1.626579e+08,334,0.000000,0.340281,4.917158e+05

Arquivo: ../data/04-gold/receita_enriquecida.parquet

Shape: (10, 48)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                 object
ds_candidato_cargo_doador                 object
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                                 str
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
nm_razao_social                           object
nm_fantasia                               object
is_cnpj_enriquecido                         bool
tp_receita                                   str
in_receita_publica                          bool
in_receita_privada                          bool
in_receita_partidaria                       bool
vl_receita_publica                       float64
vl_receita_privada                       float64
vl_receita_partidaria                    float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,42.35,0.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,39.75,0.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,42.35,0.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,39.75,0.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,13405866000124,NOVO,...,None,None,False,PRIVADA,False,True,False,0.0,50.00,0.0
5,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,54956495000156,PC DO B,...,None,None,False,PRIVADA,False,True,False,0.0,300.00,0.0
6,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,73282907000164,PSTU,...,None,None,False,PRIVADA,False,True,False,0.0,380.00,0.0
7,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,817.08,0.0
8,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,30.00,0.0
9,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,00676262000170,PT,...,None,None,False,PRIVADA,False,True,False,0.0,84.00,0.0

In [4]:
from IPython.display import display
import duckdb

for file in PARQUET_SILVER_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        LIMIT 100
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    display(df.head())

Arquivo: ../data/03-silver/classificacao_despesa.parquet

Shape: (100, 2)

Colunas:
nm_despesa    str
tp_gasto      str
dtype: object

Amostra:

                                          nm_despesa        tp_gasto
0  DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCE...  ADMINISTRATIVO
1  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
2  TRANSFERENCIAS FINANCEIRAS EFETUADAS - OUTROS ...  ADMINISTRATIVO
3  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...  ADMINISTRATIVO
4  TRANSFERENCIAS FINANCEIRAS EFETUADAS - FUNDO P...     FINALÍSTICO

Arquivo: ../data/03-silver/cnpj.parquet

Shape: (100, 28)

Colunas:
cd_cnpj                       str
nm_razao_social               str
nm_fantasia                   str
dt_abertura                   str
ed_uf                         str
nm_regiao_politica            str
nm_tipo_estabelecimento       str
dt_situacao_cadastral         str
nm_situacao_cadastral         str
dt_sit_especial            object
nm_situacao_especial       object
cd_natureza_juridica          str
nm_natureza_juridica          str
nm_porte                      str
vl_capital_social             str
cd_cnae                       str
in_principal                  str
cd_nivel1_secao               str
nm_nivel1_secao               str
cd_nivel2_divisao             str
nm_nivel2_divisao             str
nm_nivel3_grupo               str
cd_nivel3_grupo               str
cd_nivel4_classe              str
nm_nivel4_classe              str
cd_nivel5_subclasse           str
nm_nivel5_subclasse           str
dt_atualizacao_pj_rfb         str
dtype: object

Amostra:

,cd_cnpj,nm_razao_social,nm_fantasia,dt_abertura,ed_uf,nm_regiao_politica,nm_tipo_estabelecimento,dt_situacao_cadastral,nm_situacao_cadastral,dt_sit_especial,...,nm_nivel1_secao,cd_nivel2_divisao,nm_nivel2_divisao,nm_nivel3_grupo,cd_nivel3_grupo,cd_nivel4_classe,nm_nivel4_classe,cd_nivel5_subclasse,nm_nivel5_subclasse,dt_atualizacao_pj_rfb
0,87537000130,COMERCIAL MALLET LTDA,NaN,1994-06-13 00:00:00,SC,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,46,"COMERCIO POR ATACADO, EXCETO VEICULOS AUTOMOTO...",COMERCIO ATACADISTA DE PRODUTOS DE CONSUMO NAO...,46.4,46.42-7,COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E ...,46.42-7/01,COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E ...,2026-04-13 05:46:14.493801000
1,124153000140,EMBALAGENS T 2 LTDA,NaN,1994-07-27 00:00:00,GO,CENTRO-OESTE,MATRIZ,2005-01-08 00:00:00,ATIVA,None,...,COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E ...,47,COMERCIO VAREJISTA,"COMERCIO VAREJISTA DE ARTIGOS CULTURAIS, RECRE...",47.6,47.61-0,"COMERCIO VAREJISTA DE LIVROS, JORNAIS, REVISTA...",47.61-0/03,COMERCIO VAREJISTA DE ARTIGOS DE PAPELARIA,2026-04-13 05:46:14.493801000
2,165731000197,FACILITY TOUR AGENCIA DE TURISMO LTDA,FACILITY TOUR,1994-08-16 00:00:00,SP,SUDESTE,MATRIZ,2004-04-24 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000
3,370353000183,PARANOA HOTEIS E TURISMO LTDA,NaN,1974-01-14 00:00:00,DF,CENTRO-OESTE,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ALOJAMENTO E ALIMENTACAO,55,ALOJAMENTO,HOTEIS E SIMILARES,55.1,55.10-8,HOTEIS E SIMILARES,55.10-8/01,HOTEIS,2026-04-13 05:46:14.493801000
4,373580000162,CYPRESS TURISMO LTDA,CYPRESS TURISMO,1994-12-30 00:00:00,RS,SUL,MATRIZ,2005-11-03 00:00:00,ATIVA,None,...,ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEME...,79,"AGENCIAS DE VIAGENS, OPERADORES TURISTICOS E S...",AGENCIAS DE VIAGENS E OPERADORES TURISTICOS,79.1,79.11-2,AGENCIAS DE VIAGENS,79.11-2/00,AGENCIAS DE VIAGENS,2026-04-13 05:46:14.493801000

Arquivo: ../data/03-silver/despesa.parquet

Shape: (100, 30)

Colunas:
dt_geracao                 datetime64[us]
hh_geracao                            str
aa_exercicio                        int64
tp_despesa                         object
cd_tp_esfera_partidaria               str
ds_tp_esfera_partidaria               str
sg_uf                                 str
cd_municipio                          str
nm_municipio                          str
nr_zona                             int64
cd_cnpj_prestador_conta               str
sg_partido                            str
nm_partido                            str
cd_tp_documento                    object
ds_tp_documento                    object
nr_documento                       object
aa_aidf                             int64
nr_aidf                               str
cd_tp_fornecedor                   object
ds_tp_fornecedor                   object
cd_cpf_cnpj_fornecedor             object
nm_fornecedor                      object
ds_gasto                           object
dt_pagamento               datetime64[us]
vl_gasto                          float64
vl_pagamento                      float64
vl_documento                      float64
cd_fonte_despesa                      str
ds_fonte_despesa                   object
sq_despesa                          int64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,cd_cpf_cnpj_fornecedor,nm_fornecedor,ds_gasto,dt_pagamento,vl_gasto,vl_pagamento,vl_documento,cd_fonte_despesa,ds_fonte_despesa,sq_despesa
0,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
1,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
2,2026-04-25,16:26:12,2025,None,2,ESTADUAL,CE,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
3,2026-04-25,16:26:12,2025,None,2,ESTADUAL,MS,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1
4,2026-04-25,16:26:12,2025,None,2,ESTADUAL,SP,-1,NaN,-1,...,None,None,None,NaT,0.0,0.0,0.0,-1,None,-1

Arquivo: ../data/03-silver/receita.parquet

Shape: (100, 38)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                              object
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,ds_tp_natureza_recurso,cd_tp_especie_recurso,ds_tp_especie_recurso,nr_recibo_doacao,nr_documento,dt_receita,ds_receita,vl_receita,aa_exercicio,ind_dt_receita_nula
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1475,None,2025-08-05,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2500.00,2025,False
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1490,None,2025-08-28,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,5000.00,2025,False
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1506,None,2025-10-01,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,2000.00,2025,False
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,1535,None,2025-12-22,TRANSFERENCIAS DE RECURSOS FINANCEIROS PARA MA...,4000.00,2025,False
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,FINANCEIRO,7,TRANSFERENCIA ELETRONICA,NaN,None,2025-04-25,SOBRAS FINANCEIRAS DE CAMPANHA - CANDIDATOS,1692.07,2025,False

In [5]:
from IPython.display import display
import duckdb

for file in PARQUET_GOLD_FILE_NAME:
    print(f"\nArquivo: {file}")

    df = duckdb.sql(
        f"""
        SELECT *
        FROM read_parquet('{file}')
        LIMIT 100
        """
    ).df()

    print("\nShape:", df.shape)
    print("\nColunas:")
    print(df.dtypes)

    print("\nAmostra:")
    display(df.head())

Arquivo: ../data/04-gold/despesa_enriquecida.parquet

Shape: (100, 41)

Colunas:
dt_geracao                   datetime64[us]
hh_geracao                              str
aa_exercicio                          int64
tp_despesa                           object
cd_tp_esfera_partidaria                 str
ds_tp_esfera_partidaria                 str
sg_uf                                   str
cd_municipio                            str
nm_municipio                            str
nr_zona                               int64
cd_cnpj_prestador_conta                 str
sg_partido                              str
nm_partido                              str
cd_tp_documento                      object
ds_tp_documento                      object
nr_documento                         object
aa_aidf                               int64
nr_aidf                                 str
cd_tp_fornecedor                     object
ds_tp_fornecedor                     object
cd_cpf_cnpj_fornecedor               object
nm_fornecedor                        object
ds_gasto                                str
dt_pagamento                 datetime64[us]
vl_gasto                            float64
vl_pagamento                        float64
vl_documento                        float64
cd_fonte_despesa                        str
ds_fonte_despesa                     object
sq_despesa                            int64
nm_razao_social                      object
nm_fantasia                          object
is_cnpj_enriquecido                    bool
tp_gasto                                str
tp_classificacao_origem                 str
in_despesa_administrativa              bool
in_despesa_finalistica                 bool
in_despesa_indefinida                  bool
vl_despesa_administrativa           float64
vl_despesa_finalistica              float64
vl_despesa_indefinida               float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,aa_exercicio,tp_despesa,cd_tp_esfera_partidaria,ds_tp_esfera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,...,nm_fantasia,is_cnpj_enriquecido,tp_gasto,tp_classificacao_origem,in_despesa_administrativa,in_despesa_finalistica,in_despesa_indefinida,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida
0,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
1,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
2,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
3,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0
4,2026-04-25,16:26:12,2025,None,1,DISTRITAL,DF,-1,NaN,-1,...,None,False,INDEFINIDO,NAO_CLASSIFICADO,False,False,True,0.0,0.0,0.0

Arquivo: ../data/04-gold/partido_ano_despesa.parquet

Shape: (34, 11)

Colunas:
sg_partido                        str
aa_exercicio                    int64
vl_despesa_total              float64
vl_despesa_administrativa     float64
vl_despesa_finalistica        float64
vl_despesa_indefinida         float64
qtd_fornecedores_unicos         int64
pct_despesa_administrativa    float64
pct_despesa_finalistica       float64
pct_despesa_indefinida        float64
ticket_medio_despesa          float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_despesa_total,vl_despesa_administrativa,vl_despesa_finalistica,vl_despesa_indefinida,qtd_fornecedores_unicos,pct_despesa_administrativa,pct_despesa_finalistica,pct_despesa_indefinida,ticket_medio_despesa
0,AGIR,2025,873771.32,685084.32,0.0,188687.00,37,78.405448,0.0,21.594552,23615.441081
1,AVANTE,2025,21884602.24,9806307.71,0.0,4566747.76,277,44.809166,0.0,20.867401,79005.784260
2,CIDADANIA,2025,4106777.89,2814476.88,0.0,827583.21,288,68.532484,0.0,20.151643,14259.645451
3,DC,2025,1954621.90,1344255.70,0.0,609566.20,94,68.773183,0.0,31.185888,20793.850000
4,DEM,2025,0.00,0.00,0.0,0.00,0,NaN,NaN,NaN,NaN

Arquivo: ../data/04-gold/partido_ano_receita.parquet

Shape: (34, 10)

Colunas:
sg_partido                   str
aa_exercicio               int64
vl_receita_total         float64
vl_receita_publica       float64
vl_receita_privada       float64
vl_receita_partidaria    float64
qtd_doadores_unicos        int64
pct_receita_publica      float64
pct_receita_privada      float64
ticket_medio_receita     float64
dtype: object

Amostra:

,sg_partido,aa_exercicio,vl_receita_total,vl_receita_publica,vl_receita_privada,vl_receita_partidaria,qtd_doadores_unicos,pct_receita_publica,pct_receita_privada,ticket_medio_receita
0,AGIR,2025,1207854.99,0.00,716425.63,467986.60,56,0.000000,59.313878,2.156884e+04
1,AVANTE,2025,53620628.37,29443076.52,260244.61,11696480.12,41,54.909980,0.485344,1.307820e+06
2,CIDADANIA,2025,11751454.30,3815505.23,501646.01,7429741.60,79,32.468366,4.268799,1.487526e+05
3,DC,2025,3523606.22,0.00,1281392.84,2234784.96,150,0.000000,36.365949,2.349071e+04
4,DEM,2025,0.00,0.00,0.00,0.00,0,NaN,NaN,NaN

Arquivo: ../data/04-gold/receita_enriquecida.parquet

Shape: (100, 48)

Colunas:
dt_geracao                        datetime64[us]
hh_geracao                                   str
cd_tp_esfera_partidaria                      str
ds_tp_espera_partidaria                      str
sg_uf                                        str
cd_municipio                              object
nm_municipio                              object
nr_zona                                  float64
cd_cnpj_prestador_conta                      str
sg_partido                                   str
nm_partido                                   str
cd_tp_origem_doacao                          str
ds_tp_origem_doacao                          str
cd_cpf_cnpj_doador                           str
nm_doador                                    str
cd_tp_esfera_partidaria_doador               str
ds_tp_esfera_partidaria_doador               str
sg_uf_doador                                 str
cd_municipio_doador                       object
nm_municipio_doador                       object
nr_zona_doador                           float64
sq_candidato_doador                      float64
nr_candidato_doador                      float64
cd_candidato_cargo_doador                    str
ds_candidato_cargo_doador                    str
cd_tp_fonte_recurso                          str
ds_tp_fonte_recurso                          str
cd_tp_natureza_recurso                       str
ds_tp_natureza_recurso                       str
cd_tp_especie_recurso                        str
ds_tp_especie_recurso                        str
nr_recibo_doacao                             str
nr_documento                              object
dt_receita                        datetime64[us]
ds_receita                                   str
vl_receita                               float64
aa_exercicio                               int64
ind_dt_receita_nula                         bool
nm_razao_social                              str
nm_fantasia                                  str
is_cnpj_enriquecido                         bool
tp_receita                                   str
in_receita_publica                          bool
in_receita_privada                          bool
in_receita_partidaria                       bool
vl_receita_publica                       float64
vl_receita_privada                       float64
vl_receita_partidaria                    float64
dtype: object

Amostra:

,dt_geracao,hh_geracao,cd_tp_esfera_partidaria,ds_tp_espera_partidaria,sg_uf,cd_municipio,nm_municipio,nr_zona,cd_cnpj_prestador_conta,sg_partido,...,nm_razao_social,nm_fantasia,is_cnpj_enriquecido,tp_receita,in_receita_publica,in_receita_privada,in_receita_partidaria,vl_receita_publica,vl_receita_privada,vl_receita_partidaria
0,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
1,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
2,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
3,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,2500.0
4,2026-04-25,16:24:44,0,NACIONAL,BR,None,None,NaN,32206989000180,AGIR,...,NaN,NaN,False,PARTIDARIA,False,False,True,0.0,0.0,5000.0